### ISSUE TITLE
Suppress all NEST startup output

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#700] opened 2017-04-04 09:49 UTC
When running simulations on large systems the user should be able to minimize the amount of output NEST is generating during startup. At the moment, I see two issues

1. NEST's welcome message
2. INFO output from the rng manager

I would hence suggest two modifications:

1. add a verbosity check round the `welcome` and `shortwelcome` calls in sli-init (https://github.com/nest/nest-simulator/blob/master/lib/sli/sli-init.sli#L2141 ff), so that the verbosity level in .nestrc is respected
2. set the default verbosity to `M_ERROR` in the LoggingManager constructor (https://github.com/nest/nest-simulator/blob/master/nestkernel/logging_manager.cpp#L39)

I am uncertain about the second change, so I would ask @jougs @heplesser to comment on this. If you agree, I can have a PR ready in no time.

**Comment by heplesser** [comment] 2017-04-04 11:11
This is essentially a duplicate of #415, but since you propose a fix here, I will close #415 in favour of this issue. Personally, I find the message from the RNG manager on startup rather irritating, too.  

Ideally, we should read the verbosity from `.nestrc` or the command line (last having higher priority) and use that as initial value for the `LoggingManager`.

**Comment by jougs** [comment] 2019-03-22 10:15
@jakobj: In #1071, I've fixed the second point you mention. Can you please file a PR for the first to substantiate your bold statement above? :muscle: :wink:

**Comment by jakobj** [comment] 2019-03-24 23:07
hmm, my 2017 self was apparently a bit ambitious. does setting verbosity via the commandline work for you for any level, e.g.,
```
echo "verbosity =" | nest --verbosity=QUIET -
```
for me it looks like the comparisons in https://github.com/nest/nest-simulator/blob/master/sli/slistartup.cc#L282 fail as soon as the verbosity level has more than three characters?!

**Comment by jougs** [comment] 2019-03-28 16:10
hmm, you might be right.

Executing
```bash
for v in ERROR QUIET FATAL; do
    nest --verbosity=$v -c "verbosity ="
done
```
gives me three times `10`. This indeed suggests that something with setting the verbosity is fishy... Could you look into this?

**Comment by jougs** [comment] 2019-11-05 12:16
Ping!

**Closed** 2020-05-07 20:36 UTC
Labels: I: No breaking change, S: Normal, T: Enhancement
