### ISSUE TITLE
Importing NEST in jupyter lab fails

### ISSUE THREAD

**Issue by maxbortone** [nest/nest-simulator#1210] opened 2019-05-28 15:53 UTC
I have installed nest in my conda environment by running
```
conda install -c conda-forge nest-simulator
```

When running the import statement 
```
import nest
```

from a jupyter lab cell I get the following error:

```
[INFO] [2019.5.28 17:39:42 /home/conda/feedstock_root/build_artifacts/nest-simulator_1558671899212/work/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2019.5.28 17:39:42 /home/conda/feedstock_root/build_artifacts/nest-simulator_1558671899212/work/nestkernel/rng_manager.cpp:284 @ Network::create_grng_] : Creating new default global RNG
python: /home/conda/feedstock_root/build_artifacts/nest-simulator_1558671899212/work/sli/scanner.cc:581: bool Scanner::operator()(Token&): Assertion `in->good()' failed.
```

I am using: 
* `jupyterlab 0.35.6`
* `nest-simulator 2.16.0`

**Comment by DylanMuir** [comment] 2019-06-17 11:13
I have the same issue in `ipython` on the mac. However, in straight `python` I can import `nest` successfully.

**Comment by jessica-mitchell** [comment] 2019-06-17 11:21
Hi, sorry the delay in responding to your question.

Jupyter-lab is currently not in the conda-forge package of nest. I'd recommend that you install jupyter lab in the same conda environment as the nest-simulator.  

 activate the environment that has nest-simulator
`conda activate NEST_ENV`
 install jupyter lab
`conda install -c conda-forge jupyterlab`
 run jupyter lab
`jupyter-lab`

With this, i was able to import nest without problems on the web console of jupyter lab (this is using Ubuntu).

**Comment by jessica-mitchell** [comment] 2019-06-17 11:27
@DylanMuir I think this is the same issue for you, ipython is not in the nest-simulator package. You can  
`conda install  ipython`  
while in the nest environment.

**Comment by DylanMuir** [comment] 2019-06-17 12:40
Thanks @jessica-mitchell, this fixed my issue for ipython.

**Comment by nosratullah** [comment] 2019-09-19 11:33
I did all the recommends above. but still, I get an error when I import nest into a jupyter-lab and the kernel restart automatically.

**Comment by jessica-mitchell** [comment] 2019-09-19 12:20
@nosratullah 
Can you please provide some additional information:
Which version of nest are you using? 
Which operating system are you on?
What is the exact error you get?
Does nest work in python for you?

**Comment by nosratullah** [comment] 2019-09-19 18:15
@jessica-mitchell thanks for respond.
nest-2.18.0
macOS Mojave 10.14.6 
I installed nest in a conda environment. I can import nest in python itself. but whenever I use ipython I get this error :
<img width="881" alt="Screen Shot 2019-09-19 at 22 43 21" src="https://user-images.githubusercontent.com/13776994/65269670-e6487e80-db2e-11e9-9e17-8d98fd616eaa.png">
whenever I lunch jupyter notebook or jupyter-lab I get this error :
<img width="543" alt="Screen Shot 2019-09-19 at 22 45 12" src="https://user-images.githubusercontent.com/13776994/65269817-2871c000-db2f-11e9-91d7-a0aab7a63a97.png">

**Comment by steffengraber** [comment] 2019-09-20 11:08
Hi  @nosratullah 
Thank you for reporting this. The problem with the conda package under MacOS still exists. As suggested in #1265 , in the meanwhile on MacOS you should prefer the manual installation or the installation with brew . 

There is also a docker image with a pre-installed Jupyter notebook. 

```
    docker run -it --rm -e LOCAL_USER_ID=`id -u $USER` --name my_app \
               -v $(pwd):/opt/data  \
               -p 8080:8080 nestsim/nest:latest notebook
```

It should be easy to install jupyter-lab.
For more options see: https://hub.docker.com/r/nestsim/nest
You'd be one of the first users. It'd be nice if you could give it a shot and report your experience.

**Comment by jessica-mitchell** [comment] 2019-09-20 11:11
Hi @nosratullah 

I don't have a mac with Mojave available with me at the moment, only Sierra, but I managed to use the conda install and import nest in jupyter-notebook without problems.

Can you remove or deactivate your current environment with nest and create a **new conda environment** with the following command:

`conda create --name ENVNAME-c conda-forge nest-simulator ipython jupyterlab`

Activate the environment, run jupyter-notebook and try to import nest.

Note:
Make sure that your path to python, jupyter and nest are all in the activated environment 
The command `which` will show you the path (something like this):
$  `which python`
   `/path/to/miniconda/envs/ENVNAME/bin/python`

**Comment by nosratullah** [comment] 2019-09-21 13:04
hi @jessica-mitchell 
unfortunately, I tried again to install both nest and Ipython in the same environment and looked in the path folder that contains both libraries in the same path. but the error still remains just like before.

**Comment by alcrene** [comment] 2020-06-24 14:53
I ran into this issue when installing NEST in a separate environment as Jupyter (which I would argue makes the most sense, since Jupyter should not be duplicated across environments – only `ipykernel`).

### Steps to reproduce the issue:

- Create two environments and activate the one with NEST:

      conda create -n jupyter-env -c conda-forge jupyter jupyterlab
      conda create -n nesttest -c conda-forge nest-simulator ipykernel
      conda activate nesttest
      python -m ipykernel install --user --name "nesttest" --display-name "Python (nesttest)"

- NEST works

  - In a console

        python
        import nest

  - In an IPython shell

        ipython
        import nest

  But not:
  - In a JupyterLab notebook

        conda activate jupyter-env
        jupyter lab

    Create a new empty notebook. Select `Python (nesttest)` as its kernel. Type

        import nest

    in a cell and execute. The result is the *Kernel Restarting* window reported above. In the terminal I get the following, again consistent with the reports above:

        [I 14:49:21.889 LabApp] Kernel started: a5ba5c0b-c4cf-415f-8f1f-45b48d8f9762
        [INFO] [2020.6.22 14:49:25 /home/conda/feedstock_root/build_artifacts/nest-simulator_1583214391779/work/nestkernel/rng_manager.cpp:217 @ Network::create_rngs_] : Creating default RNGs
        [INFO] [2020.6.22 14:49:25 /home/conda/feedstock_root/build_artifacts/nest-simulator_1583214391779/work/nestkernel/rng_manager.cpp:260 @ Network::create_grng_] : Creating new default global RNG
        python: /home/conda/feedstock_root/build_artifacts/nest-simulator_1583214391779/work/sli/scanner.cc:581: bool Scanner::operator()(Token&): Assertion `in->good()' failed.
        [I 14:49:27.889 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
    kernel a5ba5c0b-c4cf-415f-8f1f-45b48d8f9762 restarted

  - In a classic Jupyter notebook.

        conda activate jupyter-env
        jupyter notebook

    (Following steps same as for JupyterLab)

### Workaround

Installing NEST within `jupyter-env` solves the problem for me.

    conda activate jupyter-env
    conda install -c conda-forge nest-simulator

Nevertheless, this means that I now have NEST installed in two locations, and apparently am using files from both locations, which seems like a bad thing. Also, this might cause issues if I have multiple conda environments using different NEST versions.

### What doesn't work

Installing `jupyter` within the `nesttest` environment doesn't help.

### Package versions

  - `python` – 3.8.3
  - `jupyter` – 1.0.0
  - `jupyterlab` – 2.1.4
  - `nest` – 2.20.0

**Comment by terhorstd** [comment] 2020-07-23 09:06
@alcrene, are you sure this is supposed to work? Assuming you run all commands in that order that you wrote, the "nest works" section is all from the `nesttest` environment, right? If you register the python kernel, how does jupyter-lab know that it needs to activate the conda environment `nesttest`? Just using the python binary from a directory of a different environment won't work, since all packet paths still point to your current environment.

I'd suggest to install all in a single environment. The kind of de-duplication that you assume as a benefit in your solution is already handled quite well by conda. Installing the same packet in different environments usually does not duplicate the packet. It gets hard-linked (if possible) and does not consume any more space.

A good read for this topic (you probably know) is also the [Managing envronments](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) in the conda manual. You could experiment with stacking `nesttest` onto `jupyter-lab` or the other way around (ref `conda config --set auto_stack <n>`), though I had some non-trivial problems keeping package dependencies consistent between the parent and child environments and would consider this at-your-own-risk.

**Note:** debugging the conda environment dependencies seems pretty far off-topic for this issue and the nest bug tracker in general. If everything works in a single environment I'd rather close this issue and discuss on the mailing list or a different issue, would you agree? Also because the original issue was resolved, for MacOS there are several workarounds.

**Comment by alcrene** [comment] 2020-07-28 08:11
It's definitely supposed to work :-P. Once you've registered a kernel, it shows up in the launcher; you can also change the kernel used by a particular notebook by clicking in the top right kernel. In fact, registering a kernel in this way is the *only* way to use a virtual environment from within Jupyter. If you simply

    conda activate nesttest
    conda install jupyterlab
    jupyter lab

this will *still* use the system Python. See [Kernels for different environments](https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments) from the IPython docs.

Installing Jupyter into every environment is a problem because Jupyter uses a global configuration. Each Jupyter installation will modify the same files in `~/.jupyter` and `~/.local/share/jupyter` (these locations are returned by `jupyter --config-dir` and `jupyter --data-dir`). As soon as Jupyter sees a version update, the installations across different environments will diverge and can start breaking each others configuration. These problems get exponentially worse once you start installing Jupyter extensions: these are compiled against your Jupyter version, installed in the environment, but configured in the global directory `.jupyter/lab/user-settings/@jupyterlab/`.

These concerns are not only academic: I used to do as you suggest, and once I had created different environments at different points in time, I ran into the compability issues mentioned above with extensions. These issues completely disappear when Jupyter is installed as intended, i.e. one installation per system or user.

I don't think stacking environments is a great solution for me: anything that makes execution less reliable or future-proof is a minus.

If you feel this is a different issue than the one above, I'm glad to open another one. I myself don't know enough about the inner workings of NEST to judge whether the interaction I outlined with conda is just a different symptom of the problem outlined above, or a different one. Either way, like I said before, the possibility of having two NEST installations in two different conda environments interact is bound to be a problem at some point.

I don't think it's necessary to go to the mailing list: For now I'm mostly toying with NEST and running other people's code, so I'm fine with the workaround I described.
![jupyter_environment_selection](https://user-images.githubusercontent.com/4419684/88637365-5e21f680-d0ba-11ea-98c1-78efbf79e644.png)

**Comment by terhorstd** [comment] 2020-11-20 08:40
This is currently under deeper investigation.

**Comment by heplesser** [comment] 2021-06-30 13:29
We have significantly revised the Python setup with NEST 3, things should work out of the box now.

**Closed by heplesser** 2021-06-30 13:29 UTC
Labels: I: No breaking change, S: High, T: Bug
