### ISSUE TITLE
Configure error 

### ISSUE THREAD

**Issue by abdultaqi** [nest/nest-simulator#498] opened 2016-09-29 06:03 UTC
I am trying to install NEST but  a particular error i am getting 

Configure: error:  Your need either std:isnan or isnan to compile NEST 

i am using Ubuntu 14.04 LTS version

**Comment by heplesser** [comment] 2016-09-29 07:22
The NEST User Mailing List (http://www.nest-simulator.org/community/) is often a better forum for questions like this.

Which version of NEST are you using? And which compiler ( `gcc --version` shows this if you are using gcc)? This shouldn't really be a problem on Ubutu 14.04.

**Comment by abdultaqi** [comment] 2016-09-29 07:26
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
NEST: v2.10.0

**Comment by heplesser** [comment] 2016-09-29 07:37
That combination should certainly work. Could you post the config.log file, probably best as compressed attachment?

**Comment by abdultaqi** [comment] 2016-09-29 13:57
i have deleted all files now i am going to try again if same thong will happen i will surely push files here thanks

**Comment by abdultaqi** [comment] 2016-10-03 06:36
[Untitled 1.docx](https://github.com/nest/nest-simulator/files/505614/Untitled.1.docx)

I had tried again but the same error is coming. Attached is the file of configuration

**Comment by heplesser** [comment] 2016-10-03 09:05
@abdultaqi I think the root of the problem is in this section of the `configure` output:
```
checking dependency style of gcc... (cached) gcc3
checking for g++... no
checking for c++... no
checking for gpp... no
checking for aCC... no
checking for CC... no
checking for cxx... no
checking for cc++... no
checking for cl.exe... no
checking for FCC... no
checking for KCC... no
checking for RCC... no
checking for xlC_r... no
checking for xlC... no
checking whether we are using the GNU C++ compiler... no
```
It seems that `configure` does not find a C++ compiler on your computer. `configure` should have given a sensible error message at this point.

To install the g++ compiler, run
```sh
sudo apt-get update
sudo apt-get install g++
```
You may also want to run 
```sh
sudo apt-get install libgsl0-dev 
```
to install the GNU Science Library providing support for more neuron models.

NB: I haven't tested the commands above since I am not running Ubuntu myself, but they should work.

**Comment by heplesser** [comment] 2016-10-03 09:06
Note  to developers: Since we have moved from autotools to CMake, there is no point in fixing the missing error message in configure.

**Comment by heplesser** [comment] 2016-11-17 14:08
Closing this since there has not been any more activity for over a month.

**Closed by heplesser** 2016-11-17 14:08 UTC
