### ISSUE TITLE
failing to run NEST + Python 3

### ISSUE THREAD

**Issue by laurentperrinet** [nest/nest-simulator#382] opened 2016-06-01 22:31 UTC
I could compile NEST wrt python3 on macosx (with homebrew) using

```
git clone https://github.com/nest/nest-simulator.git
cd nest-simulator
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/bin/nest -DPYTHON_EXECUTABLE=/usr/local/python3 -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/include/python3.5m/ -DPYTHON_LIBRARY=/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5.dylib .
make
make install
```

(see http://blog.invibe.net/posts/2016-06-01-compiling-and-using-pynn-%2B-nest-%2B-python3.html)
but I fail running an example:

```
 /usr/local/nest/share/doc/nest/examples/pynest on git:master o [0:19:37]
$ ipython balancedneuron.py
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/nest/share/doc/nest/examples/pynest/balancedneuron.py in <module>()
     44 from scipy.optimize import bisect
     45
---> 46 import nest
     47 import nest.voltage_trace
     48

/usr/local/nest/lib/python3.5/site-packages/nest/__init__.py in <module>()
     55     sys.setdlopenflags(ctypes.RTLD_GLOBAL)
     56
---> 57 from . import pynestkernel as _kernel      # noqa
     58 from .lib import hl_api_helper as hl_api   # noqa
     59

ImportError: dlopen(/usr/local/nest/lib/python3.5/site-packages/nest/pynestkernel.so, 8): Symbol not found: __ZNK12lockPTRDatumIN4nest12AbstractMaskEXadL_ZNS0_14TopologyModule8MaskTypeEEEE4infoERNSt3__113basic_ostreamIcNS4_11char_traitsIcEEEE
  Referenced from: /usr/local/nest/lib/python3.5/site-packages/nest/pynestkernel.so
  Expected in: flat namespace
 in /usr/local/nest/lib/python3.5/site-packages/nest/pynestkernel.so
```

any guidance is welcome!

**Comment by heplesser** [comment] 2016-06-02 06:23
@meduz We just added a formula for nest to Homebrew, so the recommended way to install NEST under OSX is now via Homebrew:

1. Add the homebrew/science tap: execute `brew tap homebrew/science`
1. For information on what options NEST has and what will be installed, execute `brew info nest`
1. To install nest with Python, execute `brew install nest --with-python`. This will install the most recent release.
1. To install the most recent Github version, use `brew install nest --with-python --HEAD`

If you want to build by hand, you must make sure that NEST does *not* use the `clang` compiler by adding `-DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5` to the `cmake` call.

**Comment by meduz** [comment] 2016-06-02 20:29
This seems perfectly timed!

As I wished to compile for python3, I used your second solution which worked perfectly.
(Sorry I could not test the brew recipe.)

Thanks a lot,
Laurent

PS: updated instructions on http://blog.invibe.net/posts/2016-06-01-compiling-and-using-pynn-%2B-nest-%2B-python3.html

**Comment by heplesser** [comment] 2016-06-03 08:29
@meduz Great, and thank you for blogging about NEST! You may want to mention that the compiler switches to cmake are only necessary on OSX; under Linux, things should work without them.

**Comment by meduz** [comment] 2016-07-02 16:14
thanks for the feedback.

Do you plan to allow for users to mention the version of python they use? Like for ``numpy``, the use of the `` brew install numpy --with-python3 `` option. 

thanls,
Laurent

PS: @heplesser I did add a mention to that point

**Comment by heplesser** [comment] 2016-07-04 11:32
@tammoippen What do you think?

**Comment by laurentperrinet** [comment] 2017-03-12 14:35
Thanks for implementing the homebrew formula with python 3. However I have some problems installing it. If I run the vanilla version, I get as expected:

```
$ brew install homebrew/science/nest
==> Reinstalling homebrew/science/nest
==> Downloading https://homebrew.bintray.com/bottles-science/nest-2.12.0_1.sierra.bottle.tar.gz
Already downloaded: /Users/lolo/Library/Caches/Homebrew/nest-2.12.0_1.sierra.bottle.tar.gz
==> Pouring nest-2.12.0_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/nest/2.12.0_1: 2,453 files, 19.2MB
```

but in the case of the py3k option, I get:

```
$ brew reinstall homebrew/science/nest  --with-python3

==> Reinstalling homebrew/science/nest --with-python3
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/nest/nest-simulator/releases/download/v2.12.0/nest-2.12.0.tar.gz
Already downloaded: /Users/lolo/Library/Caches/Homebrew/nest-2.12.0.tar.gz
==> cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/Cellar/nest/2.12.0_1 -Dwith-python=3
==> make
Last 15 lines from /Users/lolo/Library/Logs/Homebrew/nest/02.make:
      sli::pool::grow(unsigned long) in allocator.cpp.o
      TokenArray::~TokenArray() in arraydatum.cc.o
      lockPTRDatum<std::vector<long, std::allocator<long> >, &SLIInterpreter::IntVectortype>::clone() const in arraydatum.cc.o
      lockPTRDatum<std::vector<double, std::allocator<double> >, &SLIInterpreter::DoubleVectortype>::clone() const in arraydatum.cc.o
      lockPTR<std::vector<long, std::allocator<long> > >::~lockPTR() in arraydatum.cc.o
      lockPTR<std::vector<long, std::allocator<long> > >::~lockPTR() in arraydatum.cc.o
      ...
  "___cxa_throw_bad_array_new_length", referenced from:
      Processes::Sysexec_aFunction::execute(SLIInterpreter*) const in processes.cc.o
      RegexpModule::RegexecFunction::execute(SLIInterpreter*) const  in sliregexp.cc.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [sli/libsli.dylib] Error 1
make[1]: *** [sli/CMakeFiles/sli_lib.dir/all] Error 2
make: *** [all] Error 2

READ THIS: http://docs.brew.sh/Troubleshooting.html


```

any idea?

**Comment by heplesser** [comment] 2017-03-13 07:57
@tammoippen Could you take a look at this?

**Comment by tammoippen** [comment] 2017-03-21 10:43
Hi @laurentperrinet and @heplesser ,

I am looking into it.

**Comment by tammoippen** [comment] 2017-03-21 11:19
@laurentperrinet 
I cannot reproduce your error. However, I created a PR on homebrew (https://github.com/Homebrew/homebrew-science/pull/5293) to get the right python3 dependancies. Maybe you can locally change these dependancies and try again:

```sh
brew edit homebrew/science/nest  # and add the   ' => "with-python3"' to numpy, scipy, matplotlib in python3 sction
```

If it still fails, please give the relevant output of `brew install --verbose homebrew/science/nest --with-python3`.

**Comment by tammoippen** [comment] 2017-03-24 19:10
Both of the nest related homebrew PR's are merged by now. @laurentperrinet , can you please state, whether there are still issues with installing nest via homebrew?

**Comment by heplesser** [comment] 2017-04-03 10:21
@laurentperrinet Do you still have problems with homebrew? If not, would you close this issue?

**Comment by heplesser** [comment] 2017-06-29 09:51
Closing due to inactivity.

**Closed by heplesser** 2017-06-29 09:51 UTC
Labels: C: Installation, I: No breaking change, P: Pending, S: High, T: Bug
