### ISSUE TITLE
CreateLayer() only creates 6 layers accurately; the seventh produces a segfault when used

### ISSUE THREAD

**Issue by harryHoward** [nest/nest-simulator#1631] opened 2020-05-29 22:14 UTC
**Describe the bug**
topology.CreateLayer() only creates 6 layers accurately; the produces a segfault (11) when used.

**To Reproduce**

import nest
from nest import topology as topo
nest.ResetKernel()
neuron = 'iaf_psc_alpha'
layerSide = 25
layerSize = [float(layerSide), float(layerSide)]
excLayerDict = {'rows'     : layerSide,
                'columns'  : layerSide,
                'extent'   : layerSize,
                'elements' : neuron} 
excLayers = topo.CreateLayer([excLayerDict, excLayerDict, excLayerDict, excLayerDict, excLayerDict, excLayerDict])
excSide = 19/2
excRect = {'rectangular': {'lower_left': [-excSide, -excSide], 'upper_right': [excSide, excSide]}}
excGauss = {'gaussian': {'sigma': excSide/2}} 
excConn = {'connection_type': 'divergent',  'mask': excRect,  'kernel':excGauss}
topo.ConnectLayers(excLayers, excLayers, excConn)
ctr = topo.FindCenterElement(excLayers[5:])
targets = topo.GetTargetNodes(ctr, excLayers[5:])
len(targets[0]) # ~126
topo.ConnectLayers(excLayers[:5], excLayers[1:], excConn)
targets = topo.GetTargetNodes(ctr, excLayers[5:])
len(targets[0]) # ~126

excLayer7 = topo.CreateLayer(excLayerDict)
topo.ConnectLayers(excLayer7, excLayer7, excConn)
ctr = topo.FindCenterElement(excLayer7)
targets = topo.GetTargetNodes(ctr, excLayer7) # segfault
len(targets[0]) # ~129

**Desktop/Environment (please complete the following information):**
 - OS: MacOS 10.13.6
 - Python-Version: 3.7.6
 - NEST-Version: 2.20
 - Installation: conda create --n NESTenv -c conda-forge nest-simulator python=3.7 spyder scipy matplotlib

**Additional context**
Running the full simulation or trying to plot a layer with its mask & kernel produces the same problem. I have also reinstalled NEST.

**Comment by harryHoward** [comment] 2020-05-30 20:13
I can confirm that the same crash occurs with a 6x2 composite layer.

**Comment by stinebuu** [comment] 2020-07-07 07:36
@harryHoward thank you for reporting this.

Unfortunately, I am not able to reproduce this on my Ubuntu 16.04 computer, so it might be a Mac problem. @heplesser could you try once you are back?

I think it should work with NEST 3.0 though, because here we no longer create several layers at once, you have to create and connect them separately. I have converted your example, so you could try using `master` if it is urgent.

```
import nest

nest.ResetKernel()

neuron = 'iaf_psc_alpha'
layerSide = 25
layerSize = [float(layerSide), float(layerSide)]
excLayerGrid = nest.spatial.grid(shape=[layerSide, layerSide], extent=layerSize)

excLayer1 = nest.Create(neuron, positions=excLayerGrid)
excLayer2 = nest.Create(neuron, positions=excLayerGrid)
excLayer3 = nest.Create(neuron, positions=excLayerGrid)
excLayer4 = nest.Create(neuron, positions=excLayerGrid)
excLayer5 = nest.Create(neuron, positions=excLayerGrid)
excLayer6 = nest.Create(neuron, positions=excLayerGrid)

excSide = 19/2
excRect = {'rectangular': {'lower_left': [-excSide, -excSide], 'upper_right': [excSide, excSide]}}
excGauss = nest.spatial_distributions.gaussian(nest.spatial.distance, std=excSide/2)


excConnDict = {'rule': 'pairwise_bernoulli',
               'mask': excRect,
               'p':excGauss}

nest.Connect(excLayer1, excLayer1, excConnDict)
nest.Connect(excLayer2, excLayer2, excConnDict)
nest.Connect(excLayer3, excLayer3, excConnDict)
nest.Connect(excLayer4, excLayer4, excConnDict)
nest.Connect(excLayer5, excLayer5, excConnDict)
nest.Connect(excLayer6, excLayer6, excConnDict)

ctr = nest.FindCenterElement(excLayer6)
targets = nest.GetTargetNodes(ctr, excLayer6)
print(len(targets[0])) # ~126

nest.Connect(excLayer6, excLayer1, excConnDict)
targets = nest.GetTargetNodes(ctr, excLayer6)
print(len(targets[0])) # ~126

excLayer7 = nest.Create(neuron, positions=excLayerGrid)
nest.Connect(excLayer7, excLayer7, excConnDict)

ctr = nest.FindCenterElement(excLayer7)
targets = nest.GetTargetNodes(ctr, excLayer7)
print(len(targets[0])) # ~134
```

**Comment by stinebuu** [comment] 2021-06-08 13:09
I am closing this as it is fixed in master.

**Closed by stinebuu** 2021-06-08 13:09 UTC
Labels: I: No breaking change, S: High, T: Bug
