### ISSUE TITLE
Inconsistent multimeter recordings in multi-threaded environment

### ISSUE THREAD

**Issue by zbarni** [nest/nest-simulator#1509] opened 2020-04-07 15:10 UTC
**Describe the bug**
When reading the recordings from different multimeters in parallel (multi-threading), the recorded times are inconsistent. When reading sequentially, in the context of the same program, the results are reliable and correct. The multimeters are initialized with the `offset` parameter, so this might be related to #1508 . Specifically, the error is related to the first recorded time, which should be at `offset`.

**To Reproduce**
These code snippets are part of a larger program (which I can make available if needed), but it error boils down to a single command, after the NEST simulation was stopped. Note that the different threads read from different devices, so there can be no interference or any change within the simulator when executing these lines. **Important: these results vary between runs, the errors occur around 50% of the time.**

Multimeter parameters which are different from the default ones:
```
offset: 0.3
interval: 0.1
```
Examples:
```

logger.info('\n\n=================================='
            '\n_get_raw_responses_from_device(): [{0}] - [{1}]'
            '\n\tNEST #1 min(times) - max(times): {2:4f} - {3:4f}'
            '\n\tNEST #2 min(times) - max(times): {4:4f} - {5:4f}'
            ' '.format(dev, label,
                       min(nest.GetStatus([dev])[0]['events']['times']), max(nest.GetStatus([dev])[0]['events']['times']),
                       min(nest.GetStatus([dev])[0]['events']['times']), max(nest.GetStatus([dev])[0]['events']['times'])))
```
gives 
```
==================================
_get_raw_responses_from_device(): [204] - [ex_I_Vm_isi_sampling]
	NEST #1 min(times) - max(times): 0.300000 - 554.200000
	NEST #2 min(times) - max(times): 0.200000 - 554.200000 
```
The recorded times should be equal in both rows.

Another example where the third reading gives different values:
```
logger.info(
            '\n\n============== direct =================='
            '\n_get_raw_responses_from_device(): [{0}] - [{1}]'
            '\n\tNEST #1 min(times) - max(times): {2:4f} - {3:4f}'
            '\n\tNEST #2 min(times) - max(times): {4:4f} - {5:4f}'
            '\n\tNEST #3 min(times) - max(times): {6:4f} - {7:4f}\n'
            .format(dev, label,
                    min(nest.GetStatus([dev])[0]['events']['times']), max(nest.GetStatus([dev])[0]['events']['times']),
                    min(nest.GetStatus([dev])[0]['events']['times']), max(nest.GetStatus([dev])[0]['events']['times']),
                    min(nest.GetStatus([dev])[0]['events']['times']), max(nest.GetStatus([dev])[0]['events']['times'])))
```
gives
```
============== direct ==================
_get_raw_responses_from_device(): [203] - [ex_E_isi_sampling]
	NEST #1 min(times) - max(times): 0.300000 - 554.200000
	NEST #2 min(times) - max(times): 0.300000 - 554.200000
	NEST #3 min(times) - max(times): 0.200000 - 554.200000   # 0.2 is wrong, should be 0.3
```
Again, the recorded times should be equal in all rows.

**Desktop/Environment (please complete the following information):**
 - OS: Linux Mint 19.2
 - Python-Version: 3.6
 - NEST-Version: 2.18, 2.20
 - Installation: barebone, with MPI

**Additional context**

**Comment by stinebuu** [comment] 2020-04-20 12:05
@zbarni Thanks for reporting this! The issue seems similar to #1409, which was fixed with #1443. That problem was not part of NEST 2.18 or NEST 2.20 though, so it don't seem to be quite the same. Could you test with current master, just to make sure the problem persists? My guess is that it will, I just want to be sure.

If the problem still persists could you give me access to your code?

**Comment by stinebuu** [comment] 2020-05-12 07:58
@zbarni Have you been able to test with current master? I am not able to reproduce your error, but that might be because I don't have your code. Could you provide it?

**Comment by zbarni** [comment] 2020-05-15 10:52
@stinebuu apologies for the long delay.. the code is part of a private project and I have to ask the project owner regarding sharing, or need a bit more time to isolate the error-related section.. unfortunately, I'll be away until the end of next week, but will share it as soon as possible afterwards.

**Comment by stinebuu** [comment] 2020-10-23 11:51
@zbarni ping!

**Comment by zbarni** [comment] 2020-11-17 14:21
@stinebuu unfortunately I'm not sure when I'll have time to provide a reproducible code for this. To avoid further hindering development, I suggest closing this issue and maybe I can reopen it (or a new one) when some code is ready.

**Comment by stinebuu** [comment] 2020-11-20 10:20
@zbarni No problem! I will close this, but feel free to open it again.

**Closed by stinebuu** 2020-11-20 10:20 UTC
Labels: I: Behavior changes, S: High, T: Bug
