### ISSUE TITLE
Implicit reordering with array slicing of NodeCollection

### ISSUE THREAD

**Issue by Silmathoron** [nest/nest-simulator#1563] opened 2020-04-29 08:01 UTC
**Describe the bug**
In [current master](https://github.com/nest/nest-simulator/commit/10ad3af021fd2ef6d999087bc3f56db6791c5db9), since the merge of #1485, ``NodeCollection`` accept array slicing but does not check for index order.
This means that it automatically reorders the result (because a ``NodeCollection`` is ordered).

**To Reproduce**
```python
import nest
nn  = nest.Create("iaf_psc_alpha", 10)
res = nn[[3, 2, 1]]
```

**Expected behavior**
Either unordered ``NodeCollection`` or error.

**EDIT:** as decided in #1570, ``NodeCollection`` should remain ordered and therefore an error should be raised.

**Comment by hakonsbm** [comment] 2020-04-30 07:46
If you provide an unordered array when slicing, you will get an ordered `NodeCollection` containing the selected nodes. I would say that that is the expected behaviour, although it should be documented better.

Because the behaviour is expected, we shouldn't raise an error in this case. Returning an unordered `NodeCollection` is not within the design of the `NodeCollection` (but we can discuss that in #1570).

Is there a use case where you need to slice a `NodeCollection` with an unordered array, and preserve the order?

**Comment by Silmathoron** [comment] 2020-04-30 07:59
@hakonsbm unless we can preserve the order, ``NodeCollection`` provides very little ways of doing meaningful "one_to_one" connections.
Compared to NEST 2, ``nest.Connect(input1, input2, conn_spec="one_to_one")`` cannot work with ``NodeCollection``, e.g. trying to connect nodes 1, 2, 3 to nodes 6, 5, 4.

**Comment by heplesser** [comment] 2020-05-01 09:41
Set to "blocked" as suggested by @Silmathoron in #1570.

**Comment by stinebuu** [comment] 2020-07-03 14:16
@Silmathoron as discussed in #1570, and error should be raced in this instance. I have removed the Blocked label, as this is not yet fixed in master.

**Closed** 2020-09-14 14:18 UTC
Labels: I: Behavior changes, S: High, T: Bug
