### ISSUE TITLE
Errors detected during the run of the NEST test suite

### ISSUE THREAD

**Issue by wangsihao** [nest/nest-simulator#768] opened 2017-06-26 20:05 UTC
[reports.zip](https://github.com/nest/nest-simulator/files/1103333/reports.zip)

**Comment by heplesser** [comment] 2017-06-27 05:14
@wangsihao Which version of NEST are you using? We have fixed some errors relating to Python3 since releasing NEST 2.12.0. Please test with the newest version of the master branch from Github. None of the test failures indicate actual problems with NEST, they are minor Python issues in the test setup.

**Comment by heplesser** [comment] 2017-06-29 07:23
Partly duplicate of #680, fixed by #681, and for the remainder a duplicate of #662. Closing.

**Closed by heplesser** 2017-06-29 07:23 UTC
Labels: C: PyNEST, I: No breaking change, P: Pending, S: Low, T: Bug
