### ISSUE TITLE
[stdp_dopamine_synapse] Multi-threading results on different dopamine concentrations

### ISSUE THREAD

**Issue by gui-miotto** [nest/nest-simulator#1242] opened 2019-06-28 14:00 UTC
**Description of problem**: The dopamine concentration seems not to be correctly calculated when running on multi-thread.

**Version-Release or Git commit**: 2.16.0 (0b07c84) and 2.18.0 (2ee42f9)

**How reproducible**: Always

**Steps to Reproduce**: Just run the following script.
```python
import nest
import numpy as np
import matplotlib.pyplot as plt

def mwe(n_threads):
    # kernel configuration    
    nest.ResetKernel()
    nest.SetKernelStatus({'local_num_threads' : n_threads })

    # create nodes
    neurons = nest.Create('iaf_psc_delta', 2)
    vt = nest.Create('volume_transmitter')
    DA_spikes = nest.Create('spike_generator', params={'spike_times' : [999.]})

    # Connections
    nest.CopyModel('stdp_dopamine_synapse', 'dopa_syn', params={
        'n' : .005, 
        'vt' : vt[0],
        })
    nest.Connect(DA_spikes, vt)
    nest.Connect(neurons, neurons, syn_spec='dopa_syn')
    synapse = nest.GetConnections(neurons[:1], neurons[1:])

    # Simulate and store dopamine concentration
    delta_t = 5.
    time = np.arange(0., 2000., delta_t)
    DA_n = []
    for _ in time:
        DA_n.append(nest.GetStatus(synapse, 'n'))
        nest.Simulate(delta_t)
    
    # plot dopamine concentration
    plt.plot(time, DA_n)
    plt.suptitle(f'Running with {n_threads} local thread(s)')
    plt.ylabel('dopamine concentration')
    plt.xlabel('time (ms)')
    plt.show()

mwe(2)
mwe(1)
```
**Actual results**:
![2threads](https://user-images.githubusercontent.com/9371512/60347045-c89acb80-99bc-11e9-9bad-e31feb3155e2.png)

**Expected results**:
![1thread](https://user-images.githubusercontent.com/9371512/60347099-e2d4a980-99bc-11e9-8590-e670f47e7596.png)

**Additional info**: Related to #410. But this issue has been long closed.

**Comment by gui-miotto** [comment] 2019-06-28 14:43
And apparently there is a test for that: [testsuite::issue-410](https://www.nest-simulator.org/helpindex/sli/testsuite::issue-410.html)

**Comment by gui-miotto** [comment] 2019-07-04 14:57
Just tested with 2.18 
Issue persists

**Comment by janhahne** [comment] 2019-07-12 18:28
@gui-miotto Thanks for reporting this issue and providing this nice reproducer. I think I located the problem here: In your example script you connect a device (that has an own instance on every thread) with an volume transmitter (which also has an own instance on every thread and in addition has global targets on different threads).

Looking at the `connect` routines in `connection_manager.cpp` a comment in the code (see lines 482 and 564) tells me that for the combination mentioned above (i.e. `not source->has_proxies() and not target->has_proxies() and not target->local_receiver()`) connections are currently not allowed and therefore not established properly. In other words: Your code above should raise the error that ` nest.Connect(DA_spikes, vt)` is a illegal connection that cannot be created. 

However, this does not happend due to two issues:
- first, for some reason the `throw IllegalConnection` exception is missing here and the connect call would instead fails silently with a `return` without actually creating any connection
- secondly, the corresponding code is unreachable due to a logical error in the if/else if statements. This is actually the reason why your code above is working at all with one thread (although this is not intended in the current implementation).

I will create a PR shortly that fixes these two issues. However, fixing this here means that your code above will no longer run at all. It would therefore be interesting if there is a particular reason why this is not implemented at the moment and if this could be easily added in ordner to make your script from above work with NEST. For now you should just connect "regular" neurons to the `volume_transmitter` and everything should be fine (there is no general problem with the implementation as in the previous issue #410).

**Comment by janhahne** [comment] 2019-07-12 18:49
@heplesser @jakobj Do you have any idea why this type of connection is not implemented at all? See my last comment here and #1254 which fixes the logical erros, but will not make it possible to run the reproducer from this issue

**Comment by gui-miotto** [comment] 2019-07-12 21:01
Thanks for the clear explanation, @janhahne 
Based on what you told me, I edited the above script to have a parrot as the middle-man between `DA_spikes` and `vt`. The issue is then gone.
I'll be using this workaround on my own simulations. Do you think this may cause other problems in a bit larger networks (a few thousands neurons)?

**Comment by janhahne** [comment] 2019-07-13 10:12
> I'll be using this workaround on my own simulations. Do you think this may cause other problems in a bit larger networks (a few thousands neurons)?

@gui-miotto This should be fine (also for larger networks) and is probably the best workaround there is.

**Comment by janhahne** [comment] 2019-08-19 14:09
Fixed with #1254.

**Comment by heplesser** [comment] 2020-04-07 09:51
Closing since this issue is fixed.

**Closed by heplesser** 2020-04-07 09:51 UTC
Labels: C: Kernel, I: No breaking change, P: Pending, S: High, T: Bug

**Comment by dizcza** [comment] 2020-08-16 16:17
@gui-miotto I'm getting an error running your code.

```python
Traceback (most recent call last):
  File "/home/ulianych/PycharmProjects/nest-robotics/mwe.py", line 41, in <module>
    mwe(2)
  File "/home/ulianych/PycharmProjects/nest-robotics/mwe.py", line 21, in mwe
    nest.Connect(DA_spikes, vt)
  File "/home/ulianych/anaconda3/envs/nest-robotics/lib/python3.7/site-packages/nest/ll_api.py", line 246, in stack_checker_func
    return f(*args, **kwargs)
  File "/home/ulianych/anaconda3/envs/nest-robotics/lib/python3.7/site-packages/nest/lib/hl_api_connections.py", line 317, in Connect
    sr('Connect')
  File "/home/ulianych/anaconda3/envs/nest-robotics/lib/python3.7/site-packages/nest/ll_api.py", line 132, in catching_sli_run
    raise exceptionCls(commandname, message)
nest.lib.hl_api_exceptions.IllegalConnection: ('IllegalConnection in Connect_g_g_D_D: Creation of connection is not possible because:\nWe do not allow to connect a device to a global receiver at the moment', 'IllegalConnection', <SLILiteral: Connect_g_g_D_D>, ': Creation of connection is not possible because:\nWe do not allow to connect a device to a global receiver at the moment')
```

How to run your code and get the figures?

I found a [similar issue](https://github.com/nest/nest-simulator/issues/651), but the solution is not described there. (The answer refers to some "proxies"; I looked them up on NEST readthedocs and could not find any info about proxies except MUSIC.)

**Comment by gui-miotto** [comment] 2020-08-17 09:09
Dear @dizcza , this code can only be run on v<=2.16. This is because the fix for this issue was to forbid a direct connection between devices and volume transmitters, as explained by @janhahne (quoted bellow). That is why you are seeing this exception (IllegalConnection). Nevertheless, if you still want to run my example code on v.2.20, you have to insert a Parrot neuron between the device and the volume transmitter. 
Read the whole issue thread for more details.

> @gui-miotto Thanks for reporting this issue and providing this nice reproducer. I think I located the problem here: In your example script you connect a device (that has an own instance on every thread) with an volume transmitter (which also has an own instance on every thread and in addition has global targets on different threads).
> 
> Looking at the `connect` routines in `connection_manager.cpp` a comment in the code (see lines 482 and 564) tells me that for the combination mentioned above (i.e. `not source->has_proxies() and not target->has_proxies() and not target->local_receiver()`) connections are currently not allowed and therefore not established properly. In other words: Your code above should raise the error that ` nest.Connect(DA_spikes, vt)` is a illegal connection that cannot be created.
> 
> However, this does not happend due to two issues:
> 
>     * first, for some reason the `throw IllegalConnection` exception is missing here and the connect call would instead fail silently with a `return` without actually creating any connection
> 
>     * secondly, the corresponding code is unreachable due to a logical error in the if/else if statements. This is actually the reason why your code above is working at all with one thread (although this is not intended in the current implementation).
> 
> 
> I will create a PR shortly that fixes these two issues. However, fixing this here means that your code above will no longer run at all. It would therefore be interesting if there is a particular reason why this is not implemented at the moment and if this could be easily added in ordner to make your script from above work with NEST. For now you should just connect "regular" neurons to the `volume_transmitter` and everything should be fine (there is no general problem with the implementation as in the previous issue #410).

**Comment by dizcza** [comment] 2020-08-17 11:53
@gui-miotto thank you
Do you mean something like this
```python
    parrot = nest.Create('parrot_neuron')
    nest.Connect(DA_spikes, parrot)
    nest.Connect(parrot, vt)
```
?

**Comment by gui-miotto** [comment] 2020-08-18 08:37
Yes. Does it work?

**Comment by dizcza** [comment] 2020-08-18 11:35
Yes, it works in terms of it reproduces the figures.
Thanks.
