### ISSUE TITLE
CMake doesn't terminate when the requested package is not found in Travis

### ISSUE THREAD

**Issue by lekshmideepu** [nest/nest-simulator#1601] opened 2020-05-15 14:13 UTC
It looks like CMake doesn't terminate when the requested package like  Python is not found in the Travis build environment.
https://travis-ci.org/github/nest/nest-simulator/jobs/686740291#L904
https://travis-ci.org/github/nest/nest-simulator/jobs/686740291#L1537
https://travis-ci.org/github/nest/nest-simulator/jobs/686740291#L1578
https://travis-ci.org/github/nest/nest-simulator/jobs/686740291#L7736

**Comment by lekshmideepu** [comment] 2020-05-27 09:38
@heplesser It doesn't look like CMake terminates when [GSL libraries are not found ](https://travis-ci.org/github/lekshmideepu/nest-simulator/jobs/691663150#L1526)although the environment variable is set ON

**Comment by heplesser** [comment] 2020-05-28 08:21
OK, so the problem is more general and we would need a way to check if NEST has been built with the components we requested. Can we query the results of CMake in a sensible way and compare with our results? Or parse the `config.h` generated?

**Comment by heplesser** [comment] 2021-06-18 06:26
@lekshmideepu Is this still relevant now that we use Github actions? The general problem, namely that NEST runs a reduced test suite when not finding, e.g., GSL, is probably independent of where we run the tests?

**Comment by heplesser** [comment] 2021-06-30 14:03
@lekshmideepu Closing for now, please re-open and rename if you still think it relevant.

**Closed by heplesser** 2021-06-30 14:03 UTC
Labels: I: No breaking change, S: High, T: Bug
