### ISSUE TITLE
python folder in unexpected location after installing NEST 3

### ISSUE THREAD

**Issue by jasperalbers** [nest/nest-simulator#2079] opened 2021-06-16 10:30 UTC
**Describe the bug**
I encountered a potential bug while trying to install NEST 3 (release) on JURECA-DC with python. The building and installing works fine without errors, however, when sourcing `nest_vars.py` afterwards and trying to `import nest`, the following error is thrown:

```
  File "my/file/path/lib/python3.8/site-packages/nest/ll_api.py", line 51, in <module>
    from . import pynestkernel as kernel      # noqa
ImportError: libnest.so: cannot open shared object file: No such file or directory
```

Upon investigation of this issue, I noticed that in prior NEST versions the install step copies the two folders `nest` and `python3.8` to `$INSTALLDIR/lib64`. In the release version of NEST 3, `nest` is still copied to the same place, however, `python3.8` is copied to `$INSTALLDIR/lib` (without 64).

**Workaround**
Manually moving the folder `python3.8` to `$INSTALLDIR/lib64` fixes this issue.

**To Reproduce**
- `git clone` NEST 3 release
- build with cmake flag `-Dwith-python=ON`
- start python kernel
- `import nest`

**Expected behavior**
Load NEST as a python module.

**Desktop/Environment (please complete the following information):**
 - OS: CentOS 8.X (also reproducible on macOS Big Sur)
 - Shell: bash (also reproducible on zsh)
 - Python-Version: 3.8
 - NEST-Version: nest-3
 - Installation: 
 ```
 --------------------------------------------------------------------------------
NEST Configuration Summary
--------------------------------------------------------------------------------

Build type          :
Target System       : Linux
Cross Compiling     : FALSE
C compiler          : GNU 9.3.0 (/p/software/jurecadc/stages/2020/software/psmpi/5.4.7-1-GCC-9.3.0/bin/mpicc)
C compiler flags    :  -O2 -Wall -fopenmp    -fdiagnostics-color=auto
C++ compiler        : GNU 9.3.0 (/p/software/jurecadc/stages/2020/software/psmpi/5.4.7-1-GCC-9.3.0/bin/mpic++)
C++ compiler flags  :  -std=c++11 -O2 -Wall -fopenmp  -fdiagnostics-color=auto
Build dynamic       : ON

Built-in modules    : models
User modules        : None
Python bindings     : Yes (Python 3.8.5: /p/software/jurecadc/stages/2020/software/Python/3.8.5-GCCcore-9.3.0/bin/python3.8)
       Includes     : /p/software/jurecadc/stages/2020/software/Python/3.8.5-GCCcore-9.3.0/include/python3.8
       Libraries    : /p/software/jurecadc/stages/2020/software/Python/3.8.5-GCCcore-9.3.0/lib/libpython3.8.so

Cython bindings     : Yes (Cython 0.29.21: /p/software/jurecadc/stages/2020/software/Python/3.8.5-GCCcore-9.3.0/bin/cython)
MPI4PY header	    : NO
Use threading       : Yes (OpenMP: -fopenmp)
Use GSL             : Yes (GSL 2.6)
    Includes        : /p/software/jurecadc/stages/2020/software/GSL/2.6-GCC-9.3.0/include
    Libraries       : /p/software/jurecadc/stages/2020/software/GSL/2.6-GCC-9.3.0/lib/libgsl.so;/p/software/jurecadc/stages/2020/software/GSL/2.6-GCC-9.3.0/lib/libgslcblas.so

Use Readline        : Yes (GNU Readline 8.0)
    Includes        : /p/software/jurecadc/stages/2020/software/libreadline/8.0-GCCcore-9.3.0/include
    Libraries       : /p/software/jurecadc/stages/2020/software/libreadline/8.0-GCCcore-9.3.0/lib/libreadline.so;/p/software/jurecadc/stages/2020/software/ncurses/6.2-GCCcore-9.3.0/lib/libncurses.so

Use libltdl         : Yes (LTDL 2.4.6)
    Includes        : /usr/include
    Libraries       : /lib64/libltdl.so

Use doxygen         : No
Use MPI             : Yes (MPI: /p/software/jurecadc/stages/2020/software/psmpi/5.4.7-1-GCC-9.3.0/bin/mpic++)
    FLAGS           :
    Includes        :
    Link Flags      :
    Libraries       :

Detailed timers     : Yes

Use MUSIC           : No
Use libneurosim     : No
Use Boost           : Yes (Boost 1.74.0)
    Includes        : /p/software/jurecadc/stages/2020/software/Boost/1.74.0-gpsmpi-2020/include
    Libraries       :

Use recording backend Arbor   : No
Use SIONlib         : No
```

**Comment by Helveg** [comment] 2021-06-16 12:12
This is probably a duplicate of #2075. Can you try to build with my fix in https://github.com/Helveg/nest-simulator/tree/python-libdir

**Comment by jasperalbers** [comment] 2021-06-16 13:35
Indeed, it is a duplicate. I can confirm that your branch fixes the issue!

**Comment by heplesser** [comment] 2021-06-16 21:18
Closing as it is a duplicate of #2075.

**Closed by heplesser** 2021-06-16 21:18 UTC
Labels: I: No breaking change, P: Duplicate, S: High, T: Bug
