### ISSUE TITLE
NEST Testsuite Summary

### ISSUE THREAD

**Issue by adamhaber** [nest/nest-simulator#373] opened 2016-05-30 18:37 UTC
Just installed NEST, ran the test suite and encountered some problems.

I'm attaching the requested logs and would be happy to answer any questions in case I can help.

[nest logs.zip](https://github.com/nest/nest-simulator/files/289971/nest.logs.zip)

**Comment by heplesser** [comment] 2016-05-30 22:23
@adamhaber Thank you for your report. Which OS, compiler, MPI library, Python version are you using?

**Comment by adamhaber** [comment] 2016-05-31 05:30
OSX 10.11.5, Python 2.7 (anaconda). How can I check for compiler version and MPI library?

**Comment by heplesser** [comment] 2016-05-31 06:41
@adamhaber I assume that you compiled with the standard compiler under OSX, which is clang. Unfortunately, NEST and clang have some issues (see #74).

The easiest way to install NEST on a Mac is to install it via the Homebrew package manager:

1. To install homebrew, follow the instructions here: http://brew.sh/
1. Then, in a terminal
    1. Add the homebrew/science tap: execute `brew tap homebrew/science`
    1. For information on what options NEST has and what will be installed, execute `brew info nest`
    1. To install nest, execute `brew install nest`

Options have to be appended, e.g. to install NEST with PyNEST execute `brew install nest --with-python`.

I will close this issue as a duplicate of #74. Generally, the [NEST User Mailing List](http://www.nest-simulator.org/community/) is a good place for advice on installation problems and similar, because more people follow it and provide feedback.

**Closed by heplesser** 2016-05-31 06:41 UTC
