### ISSUE TITLE
Step_current_generator: offset usage is inconsistent with other devices

### ISSUE THREAD

**Issue by flinz** [nest/nest-simulator#277] opened 2016-03-15 12:50 UTC
The way the ``step_current_generator`` uses the device->origin value is different from e.g. the ``poisson_generator``, in that it does not shift the amplitude times relative to ``origin``, but simply [ignores the current generator for times < origin](https://github.com/nest/nest-simulator/blob/master/models/step_current_generator.cpp#L144).

See the plot below, for two such generators with similar "start" and "stop" times and a shifted origin. Script follows below.

![figure_1](https://cloud.githubusercontent.com/assets/97735/13778221/d61c04b4-eab4-11e5-9438-2159a7cf86d1.png)

```python
import nest
import matplotlib.pyplot as plt

offset = 60.
input_start = 10.
input_stop = 110.

def sim(curr, label):
    n = nest.Create("iaf_neuron", 1, {"I_e": 0.})
    mm = nest.Create("multimeter")
    nest.SetStatus(mm, {"withtime": True, "record_from": ["V_m"]})
    nest.Connect(mm, n)
    nest.Connect(curr, n)
    nest.Simulate(offset + 200.)
    ev = nest.GetStatus(mm)[0]["events"]
    plt.plot(ev["times"], ev["V_m"], label=label)

nest.ResetKernel()
nest.set_verbosity("M_ERROR")
curr = nest.Create("step_current_generator", 1, {
       "amplitude_times": [input_start, input_stop],
       "amplitude_values": [100., 0.],
       "origin": offset
   }
)
sim(curr, label="STEP")

nest.ResetKernel()
nest.set_verbosity("M_ERROR")
curr = nest.Create("poisson_generator", 1, {
       "start": input_start,
       "stop": input_stop,
       "rate": 50000.,
       "origin": offset,
   }
)
sim(curr, label="POISSON")

plt.plot([offset + input_start, offset + input_start], [-70, -60], label='start')
plt.plot([offset + input_stop, offset + input_stop], [-70, -60], label='stop')
plt.legend()
plt.show()

```

**Comment by heplesser** [comment] 2016-03-15 14:34
@flinz It's not a bug, it's a feature, although one that could be described better in the documentation.

`origin`, `start` and `stop` only define a mask on the output (or, for recording devices, the input), of a device, in the sense that the device will only provide output in the interval from `origin+start` to `origin+stop`. The variables do not in any way influence what is being output in this interval. You could use them, e.g., to periodically stimulate with a burst of Poisson spikes:
``` 
pg  = nest.Create('poisson_generator', params={'start': 10., 'stop': 20., 'rate': 1000.})
n = nest.Create('iaf_neuron')
nest.Connect(pg, n)
for k in range(10):
  nest.SetStatus(pg, {'origin': k * 100.})
  nest.Simulate(100)
```
would stimulate the neuron with a 10 ms long burst every 100 ms.

**Comment by flinz** [comment] 2016-03-16 07:59
@heplesser if this is intended, then I will close the issue. My point was, that do exactly the same paradigm as in your example for a step current generator, one would have to use 

```python
sg  = nest.Create('step_current_generator', params={"amplitude_values": [100., 0.]})
for k in range(10):
  nest.SetStatus(sg, {'origin': k * 100., "amplitude_times": [10.+k*100., 20.+k*100.]})
  nest.Simulate(100)
```

This difference in handling (i.e. having to set additionally the amplitude_times in absolute time) caused a little confusion yesterday, and, as you said, maybe should be better documented.

**Comment by heplesser** [comment] 2016-03-16 08:11
@flinz Yes, that is exactly what you need to do. I will create a new issue to remind us about improving the device documentation. I'll close this issue now.

**Closed by heplesser** 2016-03-16 08:11 UTC
