### ISSUE TITLE
mac install brew tap brewsci/science error

### ISSUE THREAD

**Issue by vin6** [nest/nest-simulator#1877] opened 2020-12-15 18:56 UTC
**Describe the bug**
A "depends_on :java" warning is thrown when tapping brewsci/science in Homebrew:

brew tap brewsci/science
==> Tapping brewsci/science
Cloning into '/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 35556 (delta 12), reused 13 (delta 5), pack-reused 35532
Receiving objects: 100% (35556/35556), 9.36 MiB | 26.69 MiB/s, done.
Resolving deltas: 100% (22666/22666), done.
Warning: Calling depends_on :java is deprecated! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/des.rb:15

**Comment by stinebuu** [comment] 2020-12-16 09:28
@vin6 Did this problem arise when you tried to install NEST?

**Comment by heplesser** [comment] 2020-12-16 14:46
@vin6 As far as I can see, your problem is a general problem with `brewsci/science`, not related to the NEST simulator. Note the `brewsci/science` is a legacy tap and no longer maintained (https://brewsci.github.io/homebrew-science/).

Since the issue is not related to NEST, I will close it.

**Closed by heplesser** 2020-12-16 14:46 UTC

**Comment by vin6** [comment] 2020-12-16 17:01
Thank you for your response. What I’m ultimately trying to install is circos, and am having a hard time finding a current formula.

--Kelly

Kelly Vining
Assistant Professor
Department of Horticulture
Oregon State University
2750 SW Campus Way
Corvallis, OR 97331
541-737-0646
