### ISSUE TITLE
nestML model creation - solver adding variables

### ISSUE THREAD

**Issue by oscr104** [nest/nest-simulator#1327] opened 2019-10-30 15:04 UTC

**Comment by clinssen** [comment] 2019-11-18 16:16
@oscr104: if you continue to run into issues, I am happy to report that the new version of ode-toolbox is now ready for beta testing. Please see my post at https://github.com/nest/nestml/issues/519#issuecomment-555087947 for instructions on how to proceed. Your comments and feedback in that thread are very much appreciated!

**Comment by oscr104** [comment] 2019-12-04 14:43
Having solved the compilation issues I was running into, I am again hitting problems with my nestml model code that I dont entirely understand. I am essentially implementing a hodgkin huxley type 2 compartment model (Alvarez et al, 2002) but during the compilation checks, I hit error messages of the following type:

[8,lc_hh_test, ERROR, <ADDED_BY_SOLVER>]: Variable 'V___d' not defined!

The problem lines seem to be the equations for the dendritic voltage ('V_d'), as removing this part of the code gets rid of the error message. The lines look like this:

V_d' = (-g_Ld * (V_d - E_Ld) - g_D*(V_d - V_s))/C_d

so very basic, passive dendrite model.

What I do not understand is why the solver is adding variables, and what I need to do to fix this issue. I have implemented the same model in python using Euler method and using Runge-Kutter python ODE solvers, so I know the equations themselves work, however maybe the formulation needs to be different for nestML?

**Comment by clinssen** [comment] 2019-12-04 21:49
Could you please post your NESTML model, so that I can attempt to reproduce the issue?

**Comment by oscr104** [comment] 2019-12-05 11:46
neuron lc_hh_test:

  state:
    r integer # number of steps in the current refractory phase
  end

  initial_values:
    V_s mV = -65. mV # somatic Membrane potential
    V_d mV = -67. mV #dendritic membrane potential
    V_m mV = -65. mV

    function alpha_n_init real = ( 0.01 * ( V_s / mV + 34. ) ) / ( 1. - exp( -0.2 * ( V_s / mV + 34. )))
    function beta_n_init  real = 0.125 * exp( -( V_s / mV + 40. ) / 80. )
    function alpha_m_init real = ( 0.1 * ( V_s / mV + 25. ) ) / ( 1. - exp( -0.1 * ( V_s / mV + 25. )) )
    function beta_m_init  real = 4. * exp( -( V_s / mV + 50. ) / 18. )
    function alpha_h_init real = 0.07 * exp( -( V_s / mV + 40. ) / 20. )
    function beta_h_init  real = 1. / ( 1. + exp( -0.1 * ( V_s / mV + 14. )) )
    function alpha_p_init real = (0.0001 * (V_s / mV + 30.)) / (1 - exp( -0.05 * (V_s + 40.)))
    function beta_p_init real = 0.004 * exp(-(V_s / mV +60.)) / 18.
    Act_m real =  alpha_m_init / ( alpha_m_init + beta_m_init )   # Activation variable m for Na
    Inact_h real = alpha_h_init / ( alpha_h_init + beta_h_init )    # Inactivation variable h for Na
    Act_n real =  alpha_n_init / ( alpha_n_init + beta_n_init ) # Activation variable n for K
    Act_p real = alpha_p_init / (alpha_p_init + beta_p_init )   # p current

    Act_m_Ca real = 1. / ( 1. + exp(-(V_s / mV + 55.) / 9.))    # Ca current activation
    Inact_y_Ca real = 1. / (1. + exp((V_s / mV + 77.) / 5.))      # Ca current inactivation
    Ca_conc real = 0.00001

  end

  equations:
    # synapses: alpha functions
    shape I_syn_in = (e/tau_syn_in) * t * exp(-t/tau_syn_in)
    shape I_syn_ex = (e/tau_syn_ex) * t * exp(-t/tau_syn_ex)

    function I_syn_exc pA = convolve(I_syn_ex, spikeExc)
    function I_syn_inh pA = convolve(I_syn_in, spikeInh)
    function I_Na  pA = g_Na * Act_m * Act_m * Act_m * Inact_h * ( V_s - E_Na )
    function I_K   pA  = g_K * Act_n * Act_n * Act_n * Act_n * ( V_s - E_K )
    function I_P  pA = g_P * Act_p * Act_p * (V_s - E_Na)
    function I_Ca pA = g_Ca * Act_m_Ca * Act_m_Ca * Inact_y_Ca * ( V_s - E_Ca )
    function I_ahp pA = g_ahp * ( Ca_conc / ( Ca_conc + 1. )) * ( V_s - E_K )
    function I_glia pA = 0.073 * (V_s  - (-80))
    function I_L   pA = g_L * ( V_s - E_L )
    #function I_D pA = g_D * ( V_s - V_d )

    V_s' =( -( I_Na + I_K + I_P  + I_L ) + currents + I_e + I_syn_inh + I_syn_exc ) / C_s
    V_d' = (-g_Ld * (V_d - E_Ld) - g_D*(V_d - V_s))/C_d  #missing gap junction coupling term

    # Act_n
    function alpha_n real = ( 0.01 * ( V_s / mV + 34. ) ) / ( 1. - exp( -0.2 * ( V_s / mV + 34. )))    # units?
    function beta_n  real = 0.125 * exp( -( V_s / mV + 40. ) / 80. )   # units?
    Act_n' = 3 * ( alpha_n * ( 1 - Act_n ) - beta_n * Act_n ) / ms   # n-variable, multiply by 3? present in original LC formula

    # Act_m
    function alpha_m real = ( 0.1 * ( V_s / mV + 25. ) ) / ( 1. - exp( -0.1 * ( V_s / mV + 25. ) / 10. ) )   # units?
    function beta_m  real = 4. * exp( -( V_s / mV + 50. ) / 18. )    # units?
    Act_m' = ( alpha_m * ( 1 - Act_m ) - beta_m * Act_m ) / ms    # m-variable

    # Inact_h'
    function alpha_h real = 0.07 * exp( -( V_s / mV + 40. ) / 20. )     # units?
    function beta_h  real = 1. / ( 1. + exp( -0.1 * ( V_s / mV + 14. )))      # units?
    Inact_h' = 3 * ( alpha_h * ( 1 - Inact_h ) - beta_h * Inact_h ) / ms    # h-variable multiply by 3? present in original LC formula

    # Act_p
    function alpha_p real = (0.0001 * (V_s / mV + 30.)) / (1 - exp( -0.05 * (V_s + 40.)))
    function beta_p real = 0.004 * exp(-(V_s / mV +60.)) / 18.       # units?
    Act_p' = (alpha_p * ( 1 - Act_p ) - beta_p * Act_p) / ms    # p variable

    #Act_m_Ca
    Act_m_Ca' = 1. / ( 1. + exp(-(V_s / mV + 55.) / 9.))/ms    # units?

    #Inact_y_Ca
    function Tau_y_Ca real = 20. + 100. / (1. + exp((V_s / mV + 76.) / 3.))     # units?
    Inact_y_Ca' = 1. / (1. + exp((V_s / mV + 77.) / Tau_y_Ca)) / ms

    # Ca concentration
    Ca_conc' = (-0.002 * 2. * ( V_s /mV - E_Ca /mV ) / ( 1. + exp( - ( V_s /mV + 25. ) / 2.5 )) - Ca_conc / 80.)/ms   # dividing out units?!
  end

  parameters:   #OPTIONS approximated into SI units from spatial units in Alvarez paper. Assumptions LC soma diameter ~30um (shimizu et al 78) .: s.a. (4pi.r^2 = ~2800um^2 = 2.8e-5cm^2)
    t_ref ms = 2.0 ms      # Refractory period

    # 0.000028cm^2   .:  LC paper values(mS/cm2) * 0.000028 / 10-6
    g_Na nS = 50.nS    # Sodium peak conductance
    g_K nS = 5.nS      # Potassium peak conductance
    g_L nS = 0.1nS          # Leak conductance
    g_Ld nS = 0.01nS  # dendritic leak conductance
    g_P nS = 0.12nS  # P current conductance
    g_ahp nS = 0.4nS
    g_Ca nS = 0.5nS
    g_D nS = 0.3nS


    # 0.000028cm^2   .:  LC paper values in uF * 0.000028 * 10-6
    C_s pF = 1 pF           #Somatic Membrane Capacitance
    C_d pF = 1 pF          # dendritic membrane capacitance

    E_Na mV = 40.mV         # Sodium reversal potential
    E_K mV = -110.mV        # Potassium reversal potential
    E_L mV = -65.mV     # Leak reversal Potential (aka resting potential)
    E_Ca mV = 140.mV
    E_Ld mV = -67.mV

    tau_syn_ex ms = 0.2ms  # Rise time of the excitatory synaptic alpha function i
    tau_syn_in ms = 2.0ms  # Rise time of the inhibitory synaptic alpha function
    I_e pA = 0.pA           # Constant Current
  end

  internals:
    RefractoryCounts integer = steps(t_ref) # refractory time in steps
  end

  input:
      spikeInh pA <- inhibitory spike
      spikeExc pA <- excitatory spike
      currents <- current
  end

  output: spike

  update:
    U_old mV = V_s
    integrate_odes()
    # sending spikes: crossing 0 mV, pseudo-refractoriness and local maximum...
    if r > 0: # is refractory?
      r -= 1
    elif V_s > 0 mV and U_old > V_s: # threshold && maximum
      r = RefractoryCounts
      emit_spike()
    end

  end

end

**Comment by oscr104** [comment] 2019-12-05 11:49
As you can probably see, it is based on the existing nestML code for the hh_psc_alpha model, with some added terms for additional ionic currents and a calcium concentration term, based on Alvarez et al 2002 paper modelling locus coeruleus neurons, plus an additional variable V_d for dendritic voltage. Eventually I will trying to add gap junction coupling to the model using the NEST gap junction functionality, but for now I am just trying to get the model to work as a single unit

**Comment by clinssen** [comment] 2019-12-18 10:26
I could not reproduce this issue with the latest ode-toolbox version (as mentioned in my first post above). Is this issue still occurring for you?

**Comment by heplesser** [comment] 2020-01-10 09:24
Closing.

**Closed by heplesser** 2020-01-10 09:24 UTC
