### ISSUE TITLE
Error during make in slistartup.cc

### ISSUE THREAD

**Issue by BiaDarkia** [nest/nest-simulator#401] opened 2016-06-16 05:52 UTC
I am trying to install NEST on arch linux, but keep receiving an error message when running make. I run the following commands for configure and make:
```
../nest-2.10.0/configure --prefix=/usr/local --without-openmp
make
```

I receive the following error message:
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../nest-2.10.0/sli -I../libnestutil -I../../nest-2.10.0/libnestutil -I../../nest-2.10.0/librandom -I../../nest-2.10.0/nestkernel -DPKGDATADIR=\"/usr/local/share/nest\" -DPKGDOCDIR=\"/usr/local/share/doc/nest\" -DPKGSOURCEDIR=\"/home/bianca/Downloads/nest-2.10.0\" -W -Wall -pedantic -Wno-long-long -O2 -MT slistartup.lo -MD -MP -MF .deps/slistartup.Tpo -c ../../nest-2.10.0/sli/slistartup.cc  -fPIC -DPIC -o .libs/slistartup.o
../../nest-2.10.0/sli/slistartup.cc: In member function 'bool SLIStartup::checkpath(const string&, std::__cxx11::string&) const':
../../nest-2.10.0/sli/slistartup.cc:75:15: error: cannot convert 'std::ifstream {aka std::basic_ifstream<char>}' to 'bool' in return
   return ( in );
               ^
Makefile:709: recipe for target 'slistartup.lo' failed
make[1]: *** [slistartup.lo] Error 1
make[1]: Leaving directory '/home/bianca/Downloads/nest-2.10.0-build/sli'
Makefile:539: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

Does anyone have any idea what may cause the issue?

**Comment by heplesser** [comment] 2016-06-16 07:51
@BiaDarkia You are probably using GCC 6 as compiler, which by default follows the C++11 standard, breaking some code. This is a duplicate of #220, which has been fixed by #389, but this was after the 2.10.0 release.

You have three options:
- Run configure adding `CXXFLAGS="-std=c++98"` to the configure line to enforce use of C++98 standard
- Pull the newest NEST sources from Github (note: they use CMake, so the configuration process is different; see the INSTALL file)
- Manually patch `slistartup.cc` [as shown here](https://github.com/nest/nest-simulator/pull/389/files)

**Comment by BiaDarkia** [comment] 2016-06-17 02:13
Thank you for the help. I tried searching for similar issues first, but didn't find the ones you are referencing. I managed to get NEST up and running by pulling the newest source code from GitHub and building with cmake.

**Comment by heplesser** [comment] 2016-06-17 07:54
@BiaDarkia Great! I will close the issue then.

**Closed by heplesser** 2016-06-17 07:54 UTC
Labels: duplicate
