### ISSUE TITLE
Segmentation fault if `Install` is called after `CopyModel`

### ISSUE THREAD

**Issue by kappeld** [nest/nest-simulator#746] opened 2017-06-08 14:39 UTC
@mhoff and I discovered a strange bug that seems to manifests whenever a custom module is loaded after a call to `CopyModel`. More precisely the following python code fails with a segmentation fault:

```
import nest
nest.CopyModel('stdp_synapse','my_synapse')
nest.Install('mymodule')
```

where `mymodule` is just the example custom module that comes with NEST.

We tested with the latest commit of NEST using `ipython3`on Debian Jessie.

I briefly looked into `ModelManager::register_connection_model_(...)`. It seems to me that the `syn_id` that is assigned to the new synapse models get messed up if the commands are called in that order.

It might make sense to prevent users from calling the commands in that order, but then the function should at least throw an exception in my opinion.

**Comment by heplesser** [comment] 2017-06-09 05:29
@kappeld @mhoff Thank you for reporting this and for your detective work! I believe the problem is [due to the following bit of code](https://github.com/nest/nest-simulator/blob/d66456ce6393e48961814444c82179fd1e52ab60/nestkernel/model_manager.cpp#L622)
```c++
ModelManager::register_connection_model_( ConnectorModel* cf )
{
  ...
  pristine_prototypes_.push_back( cf );
  const synindex syn_id = prototypes_[ 0 ].size();
  pristine_prototypes_[ syn_id ]->set_syn_id( syn_id );
```
`pristine_prototypes_` keeps unmodified copies of the original model prototypes, so that `ResetKernel` can restore `prototypes_`. `CopyModel` only adds new models to `prototypes_`, not to `pristine_prototypes_`.  If models have been created with `CopyModel`, `prototypes_` will be longer than `pristine_prototypes_` and the `syn_id` will be indexing a non-existing entry in `pristine_prototypes_`.

I'd suggest the following solution:
1. Use protected vector access in the last line above, i.e., `pristine_prototypes_.at( syn_id )->set_syn_id( syn_id );`
1. Write a regression test based on your example above. With the `at()` in place, it will reliably break.
1. Modify [`LoadModuleFunction`](https://github.com/nest/nest-simulator/blob/d66456ce6393e48961814444c82179fd1e52ab60/nestkernel/dynamicloader.cpp#L154) to prohibit loading of modules except at the beginning of a "session", i.e., before any models have been copied, neurons created, simulations run; this is a bit overly strict, but it is safe and will not inconvenience users unduly.

Other solutions would be far more complicated. One could consider the following modification of the code above:
```c++
  pristine_prototypes_.push_back( cf );
  const synindex syn_id = prototypes_[ 0 ].size();
  // pristine_prototypes_[ syn_id ]->set_syn_id( syn_id );
  pristine_prototypes_.rbegin()->set_syn_id( syn_id );
```
This would correctly set `syn_id` on the last entry of `pristine_prototypes_`, but if a `CopyModel` has been executed before installing the new module, we will end up with non-contiguous synapse ids in `pristine_prototypes_`.  When we then regenerate `prototypes_` during the next `ResetKernel`,  we would be in a lot of trouble, because NEST in many places assumes that `syn_id`s form a contiguous range.

**Closed** 2017-08-07 15:32 UTC
Labels: C: Kernel, I: No breaking change, P: In progess, S: High, T: Bug
