### ISSUE TITLE
Review current input and its documentation in iaf_psc_exp

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#101] opened 2015-09-09 09:05 UTC
`iaf_psc_exp` handles current input supplied via `CurrentEvent`s differently than other neuron models. Input via rport 0 is handled the normal way, while input via rport 1 is filtered as excitatory synaptic input.
This behavior is documented in one sentence, but that sentence is too little visible for an additional feature such at this. It should at least be on a line of its own, probably be `Remark`.

I am also struggling to understand the physical basis of this filtering. An arriving spike releases transmitter vesicles which dock at receptors and thus evoke an input current. The exponential decay of the current captures the process in which "all" channels open instantly and then close over time as transmitter molecules detach again. Thus, there is a physical basis for a current that persists beyond the arrival time of the spike.

But when we inject currents via `CurrentEvent`s, we model injection of currents via an electrode. Consider now a case where the electrode injects current only during a single time step. Then, immediately after that time step, the physical input current to the neuron is zero. But in the "filtered current" model, this current would persist as an exponentially decaying current for several milliseconds. What is the model behind this? It should be explained in the documentation.  If one just wants to have a possiblity of injecting a low-pass filtered current into a neuron, one could use `step_current_generator`, setting the current amplitudes to filtered values.

@jschuecker, could you take a look at this?

**Comment by jschuecker** [comment] 2015-09-09 11:06
This filtering of the current is motivated by the diffusion approximation, i.e. replacing the incoming  spike-trains with a gaussian white noise. This noise has to be filtered by the synapse. I implemented this to prove our newly developed theory about neurons subjected to coloured noise, caused by synaptic filtering. Is this explanation satisfactory? 

I will improve the documentation.

**Comment by sanjayankur31** [comment] 2016-06-15 13:28
This one is fixed - needs closing @heplesser , @jschuecker

**Closed** 2016-06-15 17:00 UTC
