### ISSUE TITLE
PyNEST nosetest fails for installation with python3

### ISSUE THREAD

**Issue by bernhardkaplan** [nest/nest-simulator#742] opened 2017-06-01 09:21 UTC
```
Phase 7: Running PyNEST tests.
------------------------------

  Using nosetests.

  Failure: ImportError (dynamic module does not define init function (initpynestkernel)) ... ERROR
  ERROR: Failure: ImportError (dynamic module does not define init function (initpynestkernel))
  ImportError: dynamic module does not define init function (initpynestkernel)
  FAILED (errors=1) 
```
System: Xubuntu 16.04.2, Linux 4.8.0-53-generic #56~16.04.1-Ubuntu

Configuration command: `cmake -DCMAKE_INSTALL_PREFIX:PATH=~/Downloads/nest-2.12.0-build ~/Downloads/nest-2.12.0 -Dwith-mpi=ON -Dwith-python=3`
Installation also fails without the python3 flag and only finishes successful when `-Dwith-python=2` is specified.

Report folder:
[nestreport.tar.gz](https://github.com/nest/nest-simulator/files/1044228/nestreport.tar.gz)

**Comment by mmagician** [comment] 2017-06-13 10:29
Same problem for me, have you found a solution yet?

**Comment by heplesser** [comment] 2017-06-13 11:36
`reports/installcheck.log` indicates that the testsuite runs Python 2.7, while NEST was built with Python 3.5:
```
Failure: ImportError (dynamic module does not define init function (initpynestkernel)) ... ERROR

======================================================================
ERROR: Failure: ImportError (dynamic module does not define init function (initpynestkernel))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/berni/Downloads/nest-2.12.0-build/lib/python3.5/site-packages/nest/__init__.py", line 70, in <module>
    from . import pynestkernel as _kernel      # noqa
ImportError: dynamic module does not define init function (initpynestkernel)
```
This explains why things work correctly when you build with `-Dwith-python=2`, because NEST is then built with and tested using Python 2.7. 

So different Python installations on your system apparently confuse NEST. Could you do the following:

1. `source <installpath>/bin/nest_vars.sh` before running `make installcheck`
1. If you have multiple Python environments, ascertain that you are running `make installcheck` from them same environment as `cmake` and `make`.
1. Post the `NEST Configuration Summary` printed by `cmake` for the configuration leading to the error you observe. Ideally, you should run `cmake` in an entirely clean directory to avoid any confusion bye CMake cache files.

**Comment by heplesser** [comment] 2017-06-13 11:38
Duplicate of #721.

**Comment by heplesser** [comment] 2017-06-29 09:29
Closing because it is a duplicate.

**Closed by heplesser** 2017-06-29 09:29 UTC
Labels: C: Installation, I: No breaking change, P: In progess, S: Low, T: Bug

**Comment by mmagician** [comment] 2017-07-17 09:18
This was indeed the problem, thanks!
