### ISSUE TITLE
Error with PyNEST installation on Travis

### ISSUE THREAD

**Issue by hakonsbm** [nest/nest-simulator#1743] opened 2020-09-02 08:52 UTC
All builds on Travis currently fail in the PyNEST installcheck stage, because of some installation error:

```
Phase 7: Running PyNEST tests
-----------------------------
  Failure: OSError (No such file /home/travis/build/nest/nest-simulator/build/nest/tests) ... ERROR
  ERROR: Failure: OSError (No such file /home/travis/build/nest/nest-simulator/build/nest/tests)
    File "/home/travis/virtualenv/python3.8.2/lib/python3.8/site-packages/nose/failure.py", line 42, in runTest
  OSError: No such file /home/travis/build/nest/nest-simulator/build/nest/tests
  FAILED (errors=1)
```
This may be related to the changes in #1623, but Travis has only started failing recently.

During `make install` there's the following error
```
running install
Checking .pth file support in /home/travis/build/nest/nest-simulator/result/lib/python3.8/site-packages/
/home/travis/virtualenv/python3.8.2/bin/python3 -E -c pass
/home/travis/virtualenv/python3.8.2/lib/python3.8/site-packages/setuptools/dist.py:466: UserWarning: The version specified ('HEAD@877ec311') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
TEST FAILED: /home/travis/build/nest/nest-simulator/result/lib/python3.8/site-packages/ does NOT support .pth files
bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /home/travis/build/nest/nest-simulator/result/lib/python3.8/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:
  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
```

@lekshmideepu @jougs Can you take a look at this?

**Comment by jougs** [comment] 2020-09-02 09:22
I'll have a look later today. Thanks for the investigation.

**Comment by lekshmideepu** [comment] 2020-09-07 10:05
I think I know what the problem is. I would do some trial and error..

**Comment by jougs** [comment] 2020-09-07 10:06
@lekshmideepu: Great! Just let me know if you need any help with this.

**Comment by jougs** [comment] 2020-09-07 12:07
@clinssen: Could this maybe be solved by a patch similar to the one from https://github.com/nest/nestml/pull/557?

**Comment by jougs** [comment] 2020-09-07 22:45
I am afraid that this was just a glitch in the matrix and is gone now. I'm therefore closing.

**Closed by jougs** 2020-09-07 22:45 UTC
Labels: I: No breaking change, S: Critical, T: Bug
