### ISSUE TITLE
Attribution Error : module 'nest' has no attribute 'sli_push'

### ISSUE THREAD

**Issue by nosratullah** [nest/nest-simulator#1271] opened 2019-08-21 06:09 UTC
Hi,
I used this [link](https://www.nest-simulator.org/py_sample/brunel_alpha_nest/) to recreate a balanced netwrok and follow the documentation,
`def LambertWm1(x):
nest.sli_push(x)
nest.sli_run('LambertWm1')
y = nest.sli_pop()
return y`

and get this error :
`module 'nest' has no attribute 'sli_push' `

**Comment by heplesser** [comment] 2019-08-21 07:10
@nosratullah I can confirm this. A work-around is as follows: Replace the function definition with
```python
def LambertWm1(x): 
     return nest.ll_api.sli_func('LambertWm1', float(x)) 
```

This issue raises several questions:
- In how many other places in examples have we forgotten to update `nest.sli_...` to `nest.ll_api.sli_...`?
- Why haven't we detected this problem with CI? We need automated testing of examples ...
- Should we provide the LambertW function as part of the high-level PyNEST API?

**Comment by hakonsbm** [comment] 2019-08-21 09:00
It looks like the example file is correct, so for this case it seems the problem is that the html files haven't been generated after the update. 

https://github.com/nest/nest-simulator/blob/4a0b53df2a2fff853d8e05bf70c9ea8819ed7585/pynest/examples/brunel_alpha_nest.py#L74-L78

However, a quick search found that there is still documentation and examples that use ``nest.sli_func()``, ``nest.sli_run()``, and ``nest.spp()``. We should definitely have automated testing of examples, and maybe also of code snippets in documentation.

And I am all for providing PyNEST API for all useful functions. I don't think users should have to use functions from `ll_api` at all. Note however that the Lambert W function is also available from SciPy.

**Comment by heplesser** [comment] 2019-08-21 11:49
@hakonsbm Thanks for checking! Could you check out the LambertW function in SciPy and see if we can replace the NEST-version with the SciPy version? After all, we also do not provide trig functions through PyNEST. My main concern would be that LambertW may be very new in SciPy and not be available in even slightly older versions.

**Comment by hakonsbm** [comment] 2019-08-21 12:32
@heplesser The Lambert W function in SciPy gives the same values (or with a difference very close to machine precision) as the NEST-version. It was also [added in the 0.8.0 version of SciPy](https://docs.scipy.org/doc/scipy/reference/release.0.8.0.html#lambert-w-function), which was released in 2010.

**Closed** 2019-08-26 10:10 UTC
Labels: C: Documentation, I: No breaking change, P: Pending, S: High, T: Bug
