### ISSUE TITLE
NEST Sonata example not runnable on EBRAINS

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2865] opened 2023-08-03 12:50 UTC
The NEST Sonata example (https://github.com/nest/nest-simulator/tree/master/pynest/examples/sonata_example) is shown with a "Try it on EBRAINS" button in the documentation (https://nest-simulator.readthedocs.io/en/stable/auto_examples/sonata_example/sonata_network.html), but when following that link one ends up with a notebook collection that does not include the `sonata_example` directory.

**Comment by jessica-mitchell** [comment] 2023-08-10 18:01
@heplesser The sonata example is now included in the nest-simulator-examples/ repo. I tested the link and it worked for me. Please check to make sure it works on your end.

**Comment by heplesser** [comment] 2023-08-18 10:26
It still does not work fully for me. There are a few challenges:

1. When I clicked on the link, I did not have a running collab on EBRAINS. I then started one, but in the environment that opened, I did not have the sonata notebook. I needed to click the "Try it on EBRAINS" button again to get the notebook. It then opened automatically.
2. The notebook was opened with a default Python environment, I had to manually change it to EBRAINS 23.06. Is there any way to set that automatically (to the latests EBRAINS release)?
3. The EBRAINS collab replaces the content of the NEST Example tab in my browser. I think it would be more user-friendly to configure the "Try it" button so that EBRAINS opens in a new tab. The way it was now I had to re-open the example page repeatedly.
4. With everything set, I could import nest, but then failed in the second cell. I think here @nicolossus may need to pitch in:
![image](https://github.com/nest/nest-simulator/assets/1059644/eb862614-96a9-451d-bab0-53d7343a34a7)

**Comment by nicolossus** [comment] 2023-08-18 10:56
I think a possible solution could be to replace

```python
base_path = Path(__file__).resolve().parent
```

with

```python
base_path = Path.cwd()
```

However, it does not seem like the SONATA files (the `300_pointneurons` directory) is uploaded in the `sonata_example` directory on EBRAINS. @jessica-mitchell Could you upload the `300_pointneurons` directory as well?

**Comment by heplesser** [comment] 2023-08-24 14:41
@jessica-mitchell  It works very nicely for me now as well, except that the plot at the end is only shown if I run
```
%matplotlib inline
```
in a cell. I assume this has something to do with overall notebook configuration. Maybe @terhorstd can comment on thils. It would be a bit annoying if we had to have this line in notebooks just for notebooks running on EBRAINS. Locally, it has been many years since I needed it. If we need it, it might be an idea to add it as a comment ("uncomment this if you don't see the plot"). How is this with other examples?

Concerning the right/left-clicking, I see you point, but in particular the arrow in front of "Try" suggest to me that this will take me somewhere else, in a new tab. But we can leave it as it is.

**Comment by jessica-mitchell** [comment] 2023-08-24 16:56
It looks like `matplotlib inline` is commonly used among the notebooks we have. I added it to the sonata_network.

**Comment by jessica-mitchell** [comment] 2023-08-25 11:34
@heplesser @nicolossus I think the issue is resolved?

**Comment by nicolossus** [comment] 2023-08-25 13:26
> Also fyi, the notebooks are located in a separate repo (`nest/nest-simulator-examples`). Currently they need to be manually updated/added, but we want to get a CI workflow that will generate the notebooks from the PyNEST examples in `nest-simulator` repo.

@jessica-mitchell Thanks, that's good to know! 

The NEST-SONATA example is now runnable on EBRAINS, so I am closing the issue.

**Closed by nicolossus** 2023-08-25 13:26 UTC
Labels: T: Bug, S: High, I: No breaking change
