### ISSUE TITLE
stdp synapses on pp_psc_delta neuron are not plastic

### ISSUE THREAD

**Issue by mdeger** [nest/nest-simulator#77] opened 2015-08-14 10:01 UTC
stdp_synapses onto pp_psc_delta neurons are apparently not plastic at the moment. I have made a simple example simulation script which is available here: 
https://github.com/mdeger/nest-simulator/blob/master/testsuite/manualtests/test_pp_psc_delta_stdp.py

The result of the script is shown in the attached pictures. Both neurons spike shortly after each spike of a sequence of spikes from the same presynaptic neuron. However, only the iaf_psc_delta neuron changes its synaptic weight, pp_psc_delta's weight is unchanged.

The only difference of the two models that I found, with respect to STDP behavior, is that archiver_length of the neurons is different. Both are instances of ArchivingNode, and this is important for STDP. However, I do not know how this different archiver_length may occur. I speculate that the problem occurs when the STDP connection is instantiated, and somehow the pp_psc_delta neuron does not increment its connection counter or so, but the iaf_psc_delta does it correctly.

Any help on the issue is appreciated.

![test_pp_psc_delta_stdp_fig1](https://cloud.githubusercontent.com/assets/11544025/9271562/338922ae-427b-11e5-91ad-5b3c50f8f1b3.png)
![test_pp_psc_delta_stdp_fig2](https://cloud.githubusercontent.com/assets/11544025/9271764/d48945de-427c-11e5-9717-79d8d0fc33b8.png)

**Comment by mdeger** [comment] 2015-08-14 10:03
the second picture was missing:

![test_pp_psc_delta_stdp_fig2](https://cloud.githubusercontent.com/assets/11544025/9271722/6516f502-427c-11e5-8e55-cf8ec31f43eb.png)

**Comment by heplesser** [comment] 2015-08-14 11:46
@mdeger Thank you for reporting this. I fear you have discovered a proper bug. The `update()` method of `pp_psc_delta` does not call `set_spiketime()` when emitting a spike, so that the synapse gets the impression that the neuron has never fired.

The same seems to be true for the following models:

- `ginzburg_neuron` and `mcculloch_pitts` (based on `binary_neuron`)
- `parrot_ps`
- `pp_psc_delta`
- `pp_pop_psc_delta`
- possibly `volume_transmitter`, if the synapse onto the volume transmitter should support plasticity

None of our tests seem to detect this problem. I will try to find time later today to write a SLI-regressiontest for this later, the main point would be to test that the `lastspike` entry is updated.

@abigailm Several of those neurons can emit multiple spikes in a single update step. Would one then have to call `set_spiketime()` multiple times (or with a multiplicity argument) so that all spikes are entered into the spike history?

**Comment by heplesser** [comment] 2015-08-14 13:48
@mdeger I have created a test (`ticket-77.sli`)) and started fixing this in my repo (https://github.com/heplesser/nest-simulator/tree/fix77-missing-set-spiketime). I am waiting for feedback from plasticity experts before fixing the `pp_*` models; I am not certain about handling multiplicity.

**Comment by mdeger** [comment] 2015-09-01 13:22
@heplesser Thank you for very much for investigating, and for finding a solution. I hope your suggestion of adding the set_spiketime call can be implemented soon, if it indeed fixes it.

**Comment by heplesser** [comment] 2015-09-02 14:05
@abigailm Ping! Could you have a look at my previously posted questions concerning this ticket?

**Comment by abigailm** [comment] 2015-10-16 12:02
Oh wow I am so slow. Sorry.
If a neuron emits multiple spikes per time step, then set_spiketime() has to be called each time, otherwise they will not be included in the history. This is assuming the spikes are distinguishable, as in, occur at different times albeit close together. If a neuron model can emit spikes with multiplicity > 1, then I guess the model developer should decide what STDP means in that context.

**Comment by heplesser** [comment] 2015-10-18 09:31
@abigailm Thanks for your feedback! Among the models setting spike event multiplicity, we can distinguish two cases: binary neurons boldly abuse the multiplicity mechanism to convey completely different information, so we can set them aside. For all other models, a multiplicity > 1 indicates more than one spike during a time step, but assuming implicitly that those spikes  occurred at slightly different times (prime example is the poisson generator). 

Now, for devices, this is no problem, since they never are targets of plastic synapses (and cannot send through plastic synapses either). `parrot_ps` should also be unproblematic, since it is precise spiking, so the offset should distinguish spikes (there may be precision issues though, since spike history handles spike time as doubles, so for very long running simulations 16 decimals may be a bit little). The real problem, I fear, are the pulsepacket (`pp_*`) models, since they both send and receive spikes with multiplicity > 1 (@mdeger, I think this is interesting for you, too), and those multiple spikes all are pinned to the grid.

I see two problems here: 

- While i think that `Archiving_Node::get_history()` will work correctly even if several spikes in the history have identical times, I am not absolutely sure about `get_K_value()` and `get_K_values()` (I don't have time right now to work this through in all detail).
- `STDPConnection::send()` does not take spike multiplicity into account at all. Thus, if a `pp_*` neuron sends a spike with multiplicity, e.g., 3, through an stdp-synapse, those three spikes will only be counted as one with respect to multiplicity.

**Comment by heplesser** [comment] 2015-11-04 08:56
@abigailm After further inspection, I now feel certain that `get_K_value()` and `get_K_values()` also will work correctly if the target neuron has sent spikes with multiplicity > 1 and registered them by multiple calls to `set_spiketime()`. The essential point is that `get_history()` test `runner->t_ <=` (and not `<`), so that it runs past multiple spikes registered with the same time and hikes their access counters, so they will be deleted from history eventually.

Further, concerning the definition of STDP for multiplicity > 1, I would propose the following: Following the suggestion by @flinz (see #82), consider a plastic synapse between two parrot neurons. As reference case, we use two precise spiking parrot neurons driven by spike trains `n*h - k*delta` with delta < h, and 1 < k < K such that K delta < h, i.e., we get K spikes in each time step (h is resolution). If we transmit the same spike trains via plain parrot neurons, they will be handled as spikes with multiplicity K. Then, in the limit delta -> 0, the weight changes observed in the synapse between the precise parrots shall converge to the weight changes observed between the plain parrots.

**Comment by heplesser** [comment] 2015-11-24 14:26
I suggest that we solve the in-depth test of STDP for multiplicity > 1 when addressing #80.

**Comment by mdeger** [comment] 2015-11-24 20:03
Thanks for the comprehensive changeset @heplesser and the test. 
Concerning pp_pop_psc_delta, and your comment above about pp_* neurons: Because pp_pop_psc_delta represents a whole population of neurons, not just a single one, I don't think it makes sense to connect to it with plastic synapses at all. For instance, every synapse on it typically sees massive postsynaptic firing activity. A synapse on pp_pop... actually means N synapses: from the pre- neuron to all N neurons in the pp_pop... population. But then STDP should change each of these synapses individually, which cannot work here, because the population is represented as a single node, with just one synaptic weight.
Considering all this, I think it is just not a good idea to allow STDP onto pp_pop_psc_delta. Moreover, because it typically spikes a lot, it might save some time to not archive its spike history. Therefore I changed pp_pop_psc_delta from an archiving_node to a node in commit 3d2c1fa3c7a2fc23c5a2aae3898a5e96f691676b.

**Comment by heplesser** [comment] 2015-11-24 22:14
@mdeger That makes sense!

**Comment by heplesser** [comment] 2015-12-21 08:47
Closing this now that #160 and #167 have been merged.

**Closed by heplesser** 2015-12-21 08:47 UTC
