### ISSUE TITLE
'fixed_indegree' connection rule does not work with volume_transmitter

### ISSUE THREAD

**Issue by alberto-antonietti** [nest/nest-simulator#651] opened 2017-02-01 14:15 UTC
I was trying to use a fixed_indegree rule to connect a group of neurons to different volume transmitters (previously I used to do this witout errors). This is the example code: 

```
import nest

MODULATORS=nest.Create('iaf_cond_exp',10)
VT=nest.Create('volume_transmitter',40)



nest.Connect(MODULATORS,VT,{'rule': 'fixed_indegree',
                            'indegree': 1,
                            "multapses": False,
                            "autapses": False},
                           {"model": "static_synapse",
                            "weight": 1.0,
                            "delay": 1.0})
```

And I got the error: 
> pynestkernel.NESTError: IllegalConnection in Connect_g_g_D_D: Creation of connection is not possible because:
> Cannot use this rule to connect to nodes without proxies (usually devices).

I can prevent the error to occur with a temporary workaround, but I would let you know about this issue.

**Comment by heplesser** [comment] 2017-02-08 22:36
@alberto-antonietti It's not a bug, it's a feature, although one that has arcane and technical reasons. For the sake of efficiency, almost all connection rules work in parallel, and it is then the parallel process responsible for a connection target that generates the necessary random numbers. This works well for normal neurons (those with proxies), since these exist only on a single process. But devices such as spike detectors or the volume transmitter are replicated on each parallel process. Therefore, to connect them, we need to create a connection on each process. For probabilistic connection rules, this would require that all parallel processes would draw the same random numbers in lockstep. This would be difficult to implement, in particularly since we usually (nodes with proxies) need different sequences of random numbers for each process. We therefore forbid randomized connections to models without proxies. The only exception is the `fixed_outdegree` rule which is not parallelized.

I close this issue now, feel free to re-open it if you have further questions.

**Closed by heplesser** 2017-02-08 22:36 UTC

**Comment by alberto-antonietti** [comment] 2017-02-08 23:44
Thanks @heplesser, now I understand the meaning of the prohibition :-) Thank you for the clarification!
