### ISSUE TITLE
(Python API) MPI deadlock when accessing kernel data

### ISSUE THREAD

**Issue by JoseJVS** [nest/nest-simulator#2741] opened 2023-04-28 12:59 UTC
**Describe the bug**
When running in a multi-MPI process environment, if a subset of the MPI processes access kernel information (i.e. through direct attribute access or GetKernelStatus function), said subset of processes will enter a deadlock state and never return.
Strangely enough this does not happen if all MPI processes access the kernel information.
I have added a minimal reproducer script but the issue can also be seen in the example microcircuit model when running with more than 1 MPI process.
In the microcircuit case, in the __setup_nest function of the Network class [network.py#L263](https://github.com/nest/nest-simulator/blob/7bb77336e9e8566fe30daa91f050ec477d3d480d/pynest/examples/Potjans_2014/network.py#L263), MPI rank 0 is supposed to print the random number generation seed and the total number of virtual processes. With more than 1 MPI processes, rank 0 is left in a deadlock while the rest of the ranks proceed with the network construction and attempt to simulate at which point the MPI library crashes. In this case, there is an error message printed out but points to a failure of an MPI_Allgather call which is misleading as the original problem is caused by rank 0 entering deadlock state.

**To Reproduce**
1. (Minimal) reproducing example
The issue can be reproduced with the following script.
```python
import nest

rank = nest.Rank()

rng_attr = nest.rng_seed
rng_get = nest.GetKernelStatus('rng_seed')

procs_func = nest.NumProcesses()
procs_attr = nest.num_processes
procs_get = nest.GetKernelStatus('num_processes')

threads_attr = nest.local_num_threads
threads_get = nest.GetKernelStatus('local_num_threads')

vps_attr = nest.total_num_virtual_procs
vps_get = nest.GetKernelStatus('total_num_virtual_procs')

print(f"rank (var): {rank}")
print(f"rank: {nest.Rank()}")

print(f"rng_attr (var): {rng_attr}")
print(f"rng_attr: {nest.rng_seed}")
print(f"rng_get (var): {rng_get}")
print(f"rng_get: {nest.GetKernelStatus('rng_seed')}")

print(f"procs_func (var): {procs_func}")
print(f"procs_func: {nest.NumProcesses()}")
print(f"procs_attr (var): {procs_attr}")
print(f"procs_attr: {nest.num_processes}")
print(f"procs_get (var): {procs_get}")
print(f"procs_get: {nest.GetKernelStatus('num_processes')}")

print(f"threads_attr (var): {threads_attr}")
print(f"threads_attr: {nest.local_num_threads}")
print(f"threads_get (var): {threads_get}")
print(f"threads_get: {nest.GetKernelStatus('local_num_threads')}")

print(f"vps_attr (var): {vps_attr}")
print(f"vps_attr: {nest.total_num_virtual_procs}")
print(f"vps_get (var): {vps_get}")
print(f"vps_get: {nest.GetKernelStatus('total_num_virtual_procs')}")

if rank % 2 == 0: # Succeeds if NumProcesses == 1 i.e only fails if not all MPI ranks access the data
    # Printing stored variables always work
    print(f"(rank {rank}) rank (var): {rank}")

    print(f"(rank {rank}) rng_attr (var): {rng_attr}")
    print(f"(rank {rank}) rng_get (var): {rng_get}")

    print(f"(rank {rank}) procs_func (var): {procs_func}")
    print(f"(rank {rank}) procs_attr (var): {procs_attr}")
    print(f"(rank {rank}) procs_get (var): {procs_get}")

    print(f"(rank {rank}) threads_attr (var): {threads_attr}")
    print(f"(rank {rank}) threads_get (var): {threads_get}")

    print(f"(rank {rank}) vps_attr (var): {vps_attr}")
    print(f"(rank {rank}) vps_get (var): {vps_get}")

    # Only Rank() and NumProcesses()  work
    n_rank = nest.Rank()

    n_procs_func = nest.NumProcesses()

    print(f"(rank {rank}) rank (new var): {n_rank}")
    print(f"(rank {rank}) rank: {nest.Rank()}")

    print(f"(rank {rank}) procs_func (new var): {procs_func}")
    print(f"(rank {rank}) procs_func: {nest.NumProcesses()}")

    # Any of these below fail
    n_rng_attr = nest.rng_seed
    n_rng_get = nest.GetKernelStatus('rng_seed')

    n_procs_attr = nest.num_processes
    n_procs_get = nest.GetKernelStatus('num_processes')

    n_threads_attr = nest.local_num_threads
    n_threads_get = nest.GetKernelStatus('local_num_threads')

    n_vps_attr = nest.total_num_virtual_procs
    n_vps_get = nest.GetKernelStatus('total_num_virtual_procs')

    print(f"(rank {rank}) rng_attr (new var): {n_rng_attr}")
    print(f"(rank {rank}) rng_attr: {nest.rng_seed}")
    print(f"(rank {rank}) rng_get (new var): {n_rng_get}")
    print(f"(rank {rank}) rng_get: {nest.GetKernelStatus('rng_seed')}")

    print(f"(rank {rank}) procs_attr (new var): {n_procs_attr}")
    print(f"(rank {rank}) procs_attr: {nest.num_processes}")
    print(f"(rank {rank}) procs_get (new var): {n_procs_get}")
    print(f"(rank {rank}) procs_get: {nest.GetKernelStatus('num_processes')}")

    print(f"(rank {rank}) threads_attr (new var): {n_threads_attr}")
    print(f"(rank {rank}) threads_attr: {nest.local_num_threads}")
    print(f"(rank {rank}) threads_get (new var): {n_threads_get}")
    print(f"(rank {rank}) threads_get: {nest.GetKernelStatus('local_num_threads')}")

    print(f"(rank {rank}) vps_attr (new var): {n_vps_attr}")
    print(f"(rank {rank}) vps_attr: {nest.total_num_virtual_procs}")
    print(f"(rank {rank}) vps_get (new var): {n_vps_get}")
    print(f"(rank {rank}) vps_get: {nest.GetKernelStatus('total_num_virtual_procs')}")

```
When changing the ```if rank % 2 == 0:``` to a loop over all ranks ```for i in range(procs_func): if rank == i:``` no deadlock happens.

2. Command to run
With "test.py" the name of the file containing the above script and N any number of MPI processes (if N == 1 then no error happens).
```shell
mpirun -np N python3 test.py
```

3. How to see error
After doing these print statements:
```python
    print(f"(rank {rank}) procs_func (new var): {procs_func}")
    print(f"(rank {rank}) procs_func: {nest.NumProcesses()}")
```
i.e.
```
(rank 0) procs_func (new var): 2
(rank 0) procs_func: 2
```
Execution no longer proceeds but does not crash and no error is printed (which is why I believe the MPI process entered a deadlock state).

**Expected behavior**
The MPI ranks accessing the kernel data should timely return and execution should continue.

**Desktop/Environment (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Shell: bash
 - Python-Version: Python 3.8.10
 - NEST-Version: 3.4 (7bb77336e9e8566fe30daa91f050ec477d3d480d)
 - Installation: from source
 
CMake output:
```shell
-- The CXX compiler identification is GNU 9.4.0
-- The C compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file mach-o/dyld.h
-- Looking for include file mach-o/dyld.h - not found
-- Looking for include file mach/mach.h
-- Looking for include file mach/mach.h - not found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for C++ include istream
-- Looking for C++ include istream - found
-- Looking for C++ include ostream
-- Looking for C++ include ostream - found
-- Looking for C++ include sstream
-- Looking for C++ include sstream - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
-- Check size of u_int16_t
-- Check size of u_int16_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of u_int64_t
-- Check size of u_int64_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Looking for NAN
-- Looking for NAN - found
-- Looking for isnan
-- Looking for isnan - found
-- Looking for M_E
-- Looking for M_E - found
-- Looking for M_PI
-- Looking for M_PI - found
-- Looking for expm1
-- Looking for expm1 - not found
-- Info: Host triple: x86_64-pc-linux 
-- Info: Target triple: x86_64-pc-linux 
-- Found Python: /usr/bin/python3.8 (found suitable version "3.8.10", minimum required is "3.8") found components: Interpreter Development.Module 
-- Found Cython: /usr/bin/cython (found suitable version "0.29.14", minimum required is "0.28.3") 
-- Found LTDL: /usr/lib/x86_64-linux-gnu/libltdl.so (found version "2.4.6") 
-- Found Readline: /usr/lib/x86_64-linux-gnu/libreadline.so (found version "8.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found GSL: /usr/include (found version "2.5") 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found PY_mpi4py: /usr/lib/python3/dist-packages/mpi4py  
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.69.0")  
-- Info: Check the abort exitcode. 
-- Info: Check the abort exitcode. 134 
-- Info: Check the segmentation fault exitcode. 
-- Info: Check the segmentation fault exitcode. 139 
-- Info: Check whether the compiler ignores cmath makros. 
-- Info: Check whether the compiler ignores cmath makros. OFF 
-- Info: Check whether the compiler does NOT include <*.h> headers ISO conformant. 
-- Info: Check whether the compiler does NOT include <*.h> headers ISO conformant. OFF 
-- Info: Check whether the compiler respects symbolic signal names in signal.h. 
-- Info: Check whether the compiler respects symbolic signal names in signal.h. OFF 
-- Info: Check static template member declaration. 
-- Info: Check static template member declaration. OFF 
-- Info: Check for STL vector capacity base unity. 
-- Info: Check for STL vector capacity base unity. ON 
-- Info: Check for STL vector capacity doubling strategy. 
-- Info: Check for STL vector capacity doubling strategy. ON 
-- Info: Check whether the compiler fails with ICE. 
-- Info: Check whether the compiler fails with ICE. OFF 
-- Info: Check if ::nan is available from cmath. 
-- Info: Check if ::nan is available from cmath. ON 
-- Info: Check if ::isnan is available from cmath. 
-- Info: Check if ::isnan is available from cmath. ON 
-- Info: Check if Random123 generators work. 
-- Info: Check if Random123 generators work. ON 
-- Info: Done configuring NEST version: 3.4.0-post0.dev0 

--------------------------------------------------------------------------------
NEST Configuration Summary
--------------------------------------------------------------------------------

Target System       : Linux
Cross Compiling     : FALSE
C compiler          : GNU 9.4.0 (/usr/bin/cc)
C compiler flags    :  -Wall -fopenmp   -pthread -O2 -fdiagnostics-color=auto
C++ compiler        : GNU 9.4.0 (/usr/bin/c++)
C++ compiler flags  :  -std=c++11 -Wall -fopenmp -pthread -O2 -fdiagnostics-color=auto
Build dynamic       : ON

Built-in modules    : models
User modules        : None

Python bindings     : Yes (Python 3.8.10: /usr/bin/python3.8)
    Includes        : /usr/include/python3.8
    Libraries       : 
    Cython          : Yes (Cython 0.29.14: /usr/bin/cython)
    MPI4Py          : Yes (/usr/lib/python3/dist-packages/mpi4py/include)

Documentation       : No

Use threading       : Yes (OpenMP: -fopenmp)

Use GSL             : Yes (GSL 2.5)
    Includes        : /usr/include
    Libraries       : /usr/lib/x86_64-linux-gnu/libgsl.so;/usr/lib/x86_64-linux-gnu/libgslcblas.so

Use Readline        : Yes (GNU Readline 8.0)
    Includes        : /usr/include
    Libraries       : /usr/lib/x86_64-linux-gnu/libreadline.so;/usr/lib/x86_64-linux-gnu/libncurses.so

Use libltdl         : Yes (LTDL 2.4.6)
    Includes        : /usr/include
    Libraries       : /usr/lib/x86_64-linux-gnu/libltdl.so

Use MPI             : Yes (MPI: /usr/bin/mpicxx)
    Includes        : /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include
    Libraries       : /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
    Compile Flags   : -pthread
    Link Flags      : -pthread
    Launcher        : /usr/bin/mpiexec -n <np> <prog> <args>

Detailed timers     : No

Use MUSIC           : No

Use libneurosim     : No

Use Boost           : Yes (Boost 1.71.0)
    Includes        : /usr/include
    Libraries       : 

Use SIONlib         : No

For details on setting specific flags for your MPI launcher command, see the
CMake documentation at https://cmake.org/cmake/help/latest/module/FindMPI.html

--------------------------------------------------------------------------------

The NEST executable will be installed to:
  /home/villamar/NEST/repos/test/install/bin/

NEST dynamic libraries and user modules will be installed to:
  /home/villamar/NEST/repos/test/install/lib/nest/

PyNEST will be installed to:
    /home/villamar/NEST/repos/test/install/lib/python3.8/site-packages

To set necessary environment variables, add the following line
to your ~/.bashrc :
  source /home/villamar/NEST/repos/test/install/bin/nest_vars.sh

--------------------------------------------------------------------------------

You can now build and install NEST with
  make
  make install
  make installcheck

If you experience problems with the installation or the use of NEST,
please see https://www.nest-simulator.org/frequently_asked_questions
or go to https://www.nest-simulator.org/community to find out how to
join the user mailing list.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/villamar/NEST/repos/test
```

**Additional context**
I am able to reproduce the issue in the JURECA-DC cluster with the same NEST version.
CMake output in JURECA-DC:
```shell
-- The CXX compiler identification is GNU 11.3.0
-- The C compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /p/software/jurecadc/stages/2023/software/GCCcore/11.3.0/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /p/software/jurecadc/stages/2023/software/GCCcore/11.3.0/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file mach-o/dyld.h
-- Looking for include file mach-o/dyld.h - not found
-- Looking for include file mach/mach.h
-- Looking for include file mach/mach.h - not found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for C++ include istream
-- Looking for C++ include istream - found
-- Looking for C++ include ostream
-- Looking for C++ include ostream - found
-- Looking for C++ include sstream
-- Looking for C++ include sstream - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
-- Check size of u_int16_t
-- Check size of u_int16_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of u_int64_t
-- Check size of u_int64_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Looking for NAN
-- Looking for NAN - found
-- Looking for isnan
-- Looking for isnan - found
-- Looking for M_E
-- Looking for M_E - found
-- Looking for M_PI
-- Looking for M_PI - found
-- Looking for expm1
-- Looking for expm1 - not found
-- Info: Host triple: x86_64-pc-linux 
-- Info: Target triple: x86_64-pc-linux 
-- Found Python: /p/software/jurecadc/stages/2023/software/Python/3.10.4-GCCcore-11.3.0/bin/python3.10 (found suitable version "3.10.4", minimum required is "3.8") found components: Interpreter Development.Module 
-- Found Cython: /p/software/jurecadc/stages/2023/software/Python/3.10.4-GCCcore-11.3.0/bin/cython (found suitable version "0.29.28", minimum required is "0.28.3") 
-- Found LTDL: /p/software/jurecadc/stages/2023/software/libtool/2.4.7-GCCcore-11.3.0/lib/libltdl.so (found version "2.4.7") 
-- Found Readline: /p/software/jurecadc/stages/2023/software/libreadline/8.1.2-GCCcore-11.3.0/lib/libreadline.so (found version "8.1") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2") 
-- Found GSL: /p/software/jurecadc/stages/2023/software/GSL/2.7-GCCcore-11.3.0/include (found version "2.7") 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found MPI_C: /p/software/jurecadc/stages/2023/software/OpenMPI/4.1.4-GCC-11.3.0/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /p/software/jurecadc/stages/2023/software/OpenMPI/4.1.4-GCC-11.3.0/lib/libmpi.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found PY_mpi4py: /p/software/jurecadc/stages/2023/software/mpi4py/3.1.4-gompi-2022a/lib/python3.10/site-packages/mpi4py  
-- Found Boost: /p/software/jurecadc/stages/2023/software/Boost/1.79.0-GCCcore-11.3.0/lib64/cmake/Boost-1.79.0/BoostConfig.cmake (found suitable version "1.79.0", minimum required is "1.69.0")  
-- Info: Check the abort exitcode. 
-- Info: Check the abort exitcode. 134 
-- Info: Check the segmentation fault exitcode. 
-- Info: Check the segmentation fault exitcode. 139 
-- Info: Check whether the compiler ignores cmath makros. 
-- Info: Check whether the compiler ignores cmath makros. OFF 
-- Info: Check whether the compiler does NOT include <*.h> headers ISO conformant. 
-- Info: Check whether the compiler does NOT include <*.h> headers ISO conformant. OFF 
-- Info: Check whether the compiler respects symbolic signal names in signal.h. 
-- Info: Check whether the compiler respects symbolic signal names in signal.h. OFF 
-- Info: Check static template member declaration. 
-- Info: Check static template member declaration. OFF 
-- Info: Check for STL vector capacity base unity. 
-- Info: Check for STL vector capacity base unity. ON 
-- Info: Check for STL vector capacity doubling strategy. 
-- Info: Check for STL vector capacity doubling strategy. ON 
-- Info: Check whether the compiler fails with ICE. 
-- Info: Check whether the compiler fails with ICE. OFF 
-- Info: Check if ::nan is available from cmath. 
-- Info: Check if ::nan is available from cmath. ON 
-- Info: Check if ::isnan is available from cmath. 
-- Info: Check if ::isnan is available from cmath. ON 
-- Info: Check if Random123 generators work. 
-- Info: Check if Random123 generators work. ON 
-- Info: Done configuring NEST version: 3.4.0-post0.dev0 

--------------------------------------------------------------------------------
NEST Configuration Summary
--------------------------------------------------------------------------------

Target System       : Linux
Cross Compiling     : FALSE
C compiler          : GNU 11.3.0 (/p/software/jurecadc/stages/2023/software/GCCcore/11.3.0/bin/cc)
C compiler flags    :  -Wall -fopenmp    -O2 -fdiagnostics-color=auto
C++ compiler        : GNU 11.3.0 (/p/software/jurecadc/stages/2023/software/GCCcore/11.3.0/bin/c++)
C++ compiler flags  :  -std=c++11 -Wall -fopenmp  -O2 -fdiagnostics-color=auto
Build dynamic       : ON

Built-in modules    : models
User modules        : None

Python bindings     : Yes (Python 3.10.4: /p/software/jurecadc/stages/2023/software/Python/3.10.4-GCCcore-11.3.0/bin/python3.10)
    Includes        : /p/software/jurecadc/stages/2023/software/Python/3.10.4-GCCcore-11.3.0/include/python3.10
    Libraries       : 
    Cython          : Yes (Cython 0.29.28: /p/software/jurecadc/stages/2023/software/Python/3.10.4-GCCcore-11.3.0/bin/cython)
    MPI4Py          : Yes (/p/software/jurecadc/stages/2023/software/mpi4py/3.1.4-gompi-2022a/lib/python3.10/site-packages/mpi4py/include)

Documentation       : No

Use threading       : Yes (OpenMP: -fopenmp)

Use GSL             : Yes (GSL 2.7)
    Includes        : /p/software/jurecadc/stages/2023/software/GSL/2.7-GCCcore-11.3.0/include
    Libraries       : /p/software/jurecadc/stages/2023/software/GSL/2.7-GCCcore-11.3.0/lib/libgsl.so;/p/software/jurecadc/stages/2023/software/GSL/2.7-GCCcore-11.3.0/lib/libgslcblas.so

Use Readline        : Yes (GNU Readline 8.1)
    Includes        : /p/software/jurecadc/stages/2023/software/libreadline/8.1.2-GCCcore-11.3.0/include
    Libraries       : /p/software/jurecadc/stages/2023/software/libreadline/8.1.2-GCCcore-11.3.0/lib/libreadline.so;/p/software/jurecadc/stages/2023/software/ncurses/6.3-GCCcore-11.3.0/lib/libncurses.so

Use libltdl         : Yes (LTDL 2.4.7)
    Includes        : /p/software/jurecadc/stages/2023/software/libtool/2.4.7-GCCcore-11.3.0/include
    Libraries       : /p/software/jurecadc/stages/2023/software/libtool/2.4.7-GCCcore-11.3.0/lib/libltdl.so

Use MPI             : Yes (MPI: /p/software/jurecadc/stages/2023/software/OpenMPI/4.1.4-GCC-11.3.0/bin/mpicxx)
    Includes        : /p/software/jurecadc/stages/2023/software/OpenMPI/4.1.4-GCC-11.3.0/include
    Libraries       : /p/software/jurecadc/stages/2023/software/OpenMPI/4.1.4-GCC-11.3.0/lib/libmpi.so
    Link Flags      : -Wl,-rpath -Wl,/p/software/jurecadc/stages/2023/software/OpenMPI/4.1.4-GCC-11.3.0/lib -Wl,-rpath -Wl,/p/software/jurecadc/stages/2023/software/hwloc/2.7.1-GCCcore-11.3.0/lib -Wl,--enable-new-dtags -L/p/software/jurecadc/stages/2023/software/hwloc/2.7.1-GCCcore-11.3.0/lib
    Launcher        : /usr/bin/srun -n <np> <prog> <args>

Detailed timers     : No

Use MUSIC           : No

Use libneurosim     : No

Use Boost           : Yes (Boost 1.79.0)
    Includes        : /p/software/jurecadc/stages/2023/software/Boost/1.79.0-GCCcore-11.3.0/include
    Libraries       : 

Use SIONlib         : No

For details on setting specific flags for your MPI launcher command, see the
CMake documentation at https://cmake.org/cmake/help/latest/module/FindMPI.html

--------------------------------------------------------------------------------

The NEST executable will be installed to:
  /p/project/cjinb33/villamar1/nest/test/install/bin/

NEST dynamic libraries and user modules will be installed to:
  /p/project/cjinb33/villamar1/nest/test/install/lib64/nest/

PyNEST will be installed to:
    /p/project/cjinb33/villamar1/nest/test/install/lib64/python3.10/site-packages

To set necessary environment variables, add the following line
to your ~/.bashrc :
  source /p/project/cjinb33/villamar1/nest/test/install/bin/nest_vars.sh

--------------------------------------------------------------------------------

You can now build and install NEST with
  make
  make install
  make installcheck

If you experience problems with the installation or the use of NEST,
please see https://www.nest-simulator.org/frequently_asked_questions
or go to https://www.nest-simulator.org/community to find out how to
join the user mailing list.

-- Configuring done
-- Generating done
-- Build files have been written to: /p/project/cjinb33/villamar1/nest/test
```

**Comment by heplesser** [comment] 2023-04-28 21:13
@JoseJVS The cause of this deadlock is that `CommunicationManager` needs to do MPI communication to get correct min/max delay information from all MPI processes to all MPI processes whenever `GetKernelStatus` is called. This applies even if one asks for entirely unrelated things, e.g., `nest.rng_seed`, because behind the scenes all kernel status info is collected for each such expression. Results are only filtered at the Python level.

**Comment by JoseJVS** [comment] 2023-04-30 09:42
I see, I did not know this was the case but then it makes sense why the deadlock is happening.
Should I close this issue then, as the API technically is working as intended but the usage is incorrect?

**Comment by heplesser** [comment] 2023-05-02 07:26
@JoseJVS Yes, please close the issue.

**Closed** 2023-05-02 10:09 UTC
Labels: T: Bug, S: High, I: No breaking change
