### ISSUE TITLE
Difficulties in installation on windows

### ISSUE THREAD

**Issue by saeidehdavoudi** [nest/nest-simulator#2413] opened 2022-06-10 20:40 UTC
Hello,

I followed the instruction for installation on windows (using virtualbox) but I cannot import the nest on that. I faced the error "failed to open a session for the virtual machine lubunta-22.04 mit nest-v3.3 2". could you please help me on that?

Thank you in advance,

S.D

**Comment by Craw-B** [comment] 2022-06-29 07:23
Nest cannot be installed on windows. You need to install it in the Linux environment. It is better to install the source code. Windows can also be installed using docker.

**Comment by steffengraber** [comment] 2022-06-29 09:37
> Failed to import appliance C:\Users\ric.VirtualBox\nest-latest.ova.

@ricardomurphy I can confirm this and will create a new VM.

@saeidehdavoudi Is it necessary to use this version, or can you switch to the latest version? 

I'll let you know as soon as the update is available.

**Comment by ricardomurphy** [comment] 2022-06-30 11:37
Unfortunately I still get the same error, both with the latest 
version of NEST and Ver. 3.1:

Failed to import appliance C:\temp\nest-latest.ova.

Result Code: E_INVALIDARG (0x80070057)

Failed to import appliance C:\temp\nest-3.1.ova.

Result Code: E_INVALIDARG (0x80070057)

This was using Ver. 6.1.34 of VirtualBox in Windows 2010. 
Ricardo
___________________________________

Dr. Ricardo Murphy,
University of Oslo,
Domus Medica,
Division of Physiology,
Pb. 1103, Blindern,
0317 Oslo

**Comment by steffengraber** [comment] 2022-06-30 11:55
@ricardomurphy Which file system do you have in Windows 2010? Fat32 only supports file sizes up to 4 GB, which is too small here.

**Comment by saeidehdavoudi** [comment] 2022-06-30 12:09
Hello,
Thanks for the guidance. At that time, I needed working with NEST urgently, so I gave up windows and I tried on LINUX but I will use this version as well. My windows is 11.


Thanks,

S.D
________________________________

**Comment by steffengraber** [comment] 2022-06-30 12:28
> Sorry, of course I meant Windows 10, not 2010. The file system is NTFS. Ricardo
@ricardomurphy Unfortunately, I don't have access to a Windows 10 system at the moment to test this. But I think these errors indicate a storage or RAM problem. How much free space do you have on your hard drive? How much RAM do you have available?

**Comment by ricardomurphy** [comment] 2022-06-30 13:40
I have around 10 GB free on my C: drive (that's with VirtualBox installed) and I put the ova file on a 1TB drive with about 700 GB free. I have a total of 12 GB RAM.
Ricardo
___________________________________

Dr. Ricardo Murphy,
University of Oslo,
Domus Medica,
Division of Physiology,
Pb. 1103, Blindern,
0317 Oslo

**Comment by ricardomurphy** [comment] 2022-06-30 14:47
Hello again.
I just managed to import nest 3.3 into VirtualBox on my Windows 10 tablet (Microsoft Surface Pro 4), which is a younger machine than my desktop. I'll test it tomorrow and let you know 
Ricardo
___________________________________

Dr. Ricardo Murphy,
University of Oslo,
Domus Medica,
Division of Physiology,
Pb. 1103, Blindern,
0317 Oslo

**Comment by steffengraber** [comment] 2022-06-30 16:50
> I just managed to import nest 3.3 into VirtualBox on my Windows 10 tablet (Microsoft Surface Pro 4), which is a younger machine than my desktop. I'll test it tomorrow and let you know

That sounds better. Thanks for your testing efforts.

**Comment by ricardomurphy** [comment] 2022-07-01 16:20
Hi,
I ran the following program in the NEST VM, taken from the "Getting Started" page of the NEST website:

import nest
import nest.voltage_trace
import matplotlib.pyplot as plt
nest.ResetKernel()

#Create the neuron models you want to simulate:

neuron = nest.Create('iaf_psc_exp')

#Create the devices to stimulate or observe the neurons in the simulation:

spikegenerator = nest.Create('spike_generator')
voltmeter = nest.Create('voltmeter')

#Modify properties of the device:

spikegenerator.set(spike_times=[10.0, 50.0])

#Connect neurons to devices and specify synapse (connection) properties:

nest.Connect(spikegenerator, neuron, syn_spec={'weight': 1e3})
nest.Connect(voltmeter, neuron)

#Simulate the network for the given time in miliseconds:

nest.Simulate(100.0)

#Display the voltage graph from the voltmeter:

nest.voltage_trace.from_device(voltmeter)
plt.show()

It produced the expected output and no error messages.
Ricardo
___________________________________

Dr. Ricardo Murphy,
University of Oslo,
Domus Medica,
Division of Physiology,
Pb. 1103, Blindern,
0317 Oslo

**Comment by steffengraber** [comment] 2022-07-04 07:14
Thanks again for testing. We should perhaps discuss our hardware requirements again.

**Comment by steffengraber** [comment] 2022-07-04 07:18
Since the issues seems to be fixed for now, I am closing the issue.

**Closed by steffengraber** 2022-07-04 07:18 UTC
Labels: T: Bug, S: Normal
