### ISSUE TITLE
cmake breaks doc build process/suggestion to set default install directory for cmake

### ISSUE THREAD

**Issue by jd41** [nest/nest-simulator#1783] opened 2020-09-26 06:02 UTC
After running `cmake` in the nest-simulator main directory according to the installation instructions, `make html` for the documentation in the `doc` folder doesn't work anymore. The problem seems to be that `cmake` changes `doc/Makefile`, and discarding the changes to that Makefile makes `make html` work again. I attached a `git diff` of the Makefile after `cmake`, [diff_makefile.txt](https://github.com/nest/nest-simulator/files/5286250/diff_makefile.txt).

I'd also like to suggest to set a default path CMAKE_INSTALL_PREFIX to, e.g., an `install` subdirectory so that just typing `cmake` will work. I realize having to set this manually is a micro-annoyance, but it's an annoyance nevertheless, and one that I guess costs people hundreds of minutes a year. If the person fixing the bug above sets such a directory (`install` already exists in the `.gitignore`, by the way) and tests the change in one go with the fix, I think it would cost them 2-5 additional minutes. I heard there is a discussion going on regarding changing the build system, but if this discussion goes on for only three more months, I think the investment would already pay off. I realize it's a separate issue from the one above, but I write it in one go nevertheless because they can be tested and reviewed together. If there is any disagreement with my suggestion, feel free to write so and then ignore this paragraph for the fix.

**Comment by stinebuu** [comment] 2020-09-30 09:49
Hi @jd41!
> After running cmake in the nest-simulator main directory according to the installation instructions, 

Could you link to where you found that cmake should be run in the nest-simulator main directory?
When installing NEST, it is best to create a separate build directory outside the source directory (see a little down [here](https://nest-simulator.readthedocs.io/en/latest/installation/linux_install.html), so if it is documented somewhere that you should do cmake in the main directory, this should be fixed.

**Comment by hakonsbm** [comment] 2020-09-30 11:29
> I'd also like to suggest to set a default path CMAKE_INSTALL_PREFIX to, e.g., an `install` subdirectory so that just typing `cmake` will work. 

The default value for `CMAKE_INSTALL_PREFIX` in CMake is already `/usr/local`. Defining a different default location than what is default for CMake would be confusing, I think.

An easy way to set the install directory to be a subdirectory is to use `-DCMAKE_INSTALL_PREFIX:PATH=$PWD/install`, where the current directory is inserted for `$PWD` automatically by the shell.

**Comment by jd41** [comment] 2020-10-02 13:20
I just noticed that this information is also included [here](https://nest-simulator.readthedocs.io/en/latest/installation/install_options.html).

**Comment by terhorstd** [comment] 2020-10-16 09:35
This is a duplicate of #1660, and the default install path was explained. closing.

**Closed by terhorstd** 2020-10-16 09:35 UTC
Labels: I: No breaking change, S: Normal, T: Maintenance
