### ISSUE TITLE
MyModule complation error with v2.10.0

### ISSUE THREAD

**Issue by obreitwi** [nest/nest-simulator#228] opened 2016-02-16 16:33 UTC
When trying to compile MyModule with NEST v2.10.0, the following compile error is thrown:

```
../MyModule/mymodule.cpp: In member function 'virtual void mynest::MyModule::StepPatternConnect_Vi_i_Vi_i_lFunction::execute(SLIInterpreter*) const':
../MyModule/mymodule.cpp:155:73: error: 'DictionaryDatum' has no member named 'lookup'
../MyModule/mymodule.cpp: In member function 'virtual void mynest::MyModule::init(SLIInterpreter*)':
../MyModule/mymodule.cpp:198:32: error: 'class nest::ModelManager' has no member named 'register_model'
../MyModule/mymodule.cpp:198:62: error: expected primary-expression before '>' token
../MyModule/mymodule.cpp:211:3: error: 'register_connection_model' is not a member of 'nest'
../MyModule/mymodule.cpp:211:93: error: expected primary-expression before '>' token
```

My best guess is that the code for MyModule was not updated to confirm to the recent internal code changes.

**Comment by tammoippen** [comment] 2016-02-18 08:53
I just tried to compile `MyModule` from NEST 2.10.0 - I could not reproduce your errors. Can you please elaborate one which steps you took to compile the module? My steps were:

    cd /path/to/MyModule
    ./bootstrap.sh
    mkdir build
    cd build
    ../configure --with-nest=/path/to/nest/2.10.0/install/bin/nest-config
    make
    make install

For more information on how to build and use external modules, please have a look at our [developer space](https://nest.github.io/nest-simulator/extension_modules).

**Comment by obreitwi** [comment] 2016-02-18 10:33
Sorry, what I meant to say was I try to compile `MyModule` against the current head (`v2.10.0-301-gc2ce466`) instead of the 2.10.0 release. It appears the example was not yet updated to the nest3 changes.

**Comment by tammoippen** [comment] 2016-02-18 13:10
I can reproduce this with c2ce466! And the errors have already been addressed in #213. When that PR is merged, MyModule works again.

**Comment by tammoippen** [comment] 2016-04-04 12:46
@obreitwi Can you please again try compiling `MyModule` of the current master? #213 is now merged and I took special care for compilability of `MyModule`. Be aware, that the build syatem changed to `cmake`.

**Comment by heplesser** [comment] 2017-06-29 08:50
Closed due to inactivity.

**Closed by heplesser** 2017-06-29 08:50 UTC
