### ISSUE TITLE
TypeMismatch error when setting a default distribution for a parameter

### ISSUE THREAD

**Issue by JimmyMVP** [nest/nest-simulator#667] opened 2017-02-28 14:55 UTC
Here is a code snippet for an example:

    nest.SetDefaults('stdp_dopamine_synapse', {'vt': vt[0], 'weight' :  {'distribution' : 'normal', 'mu' : 0., 'sigma' : 1.}})

and the error:

terminate called after throwing an instance of 'TypeMismatch'
  what():  TypeMismatch
[bluebrain285:44128] *** Process received signal ***
[bluebrain285:44128] Signal: Abort trap: 6 (6)
[bluebrain285:44128] Signal code:  (0)
[bluebrain285:44128] [ 0] 0   libsystem_platform.dylib            0x00007fffa282abba _sigtramp + 26
[bluebrain285:44128] [ 1] 0   ???                                 0x0000000100000001 0x0 + 4294967297
[bluebrain285:44128] [ 2] 0   libsystem_c.dylib                   0x00007fffa26b1420 abort + 129
[bluebrain285:44128] [ 3] 0   libstdc++.6.dylib                   0x0000000109292c54 _ZN9__gnu_cxx27__verbose_terminate_handlerEv + 324
[bluebrain285:44128] *** End of error message ***

**Comment by heplesser** [comment] 2017-02-28 22:44
@JimmyMVP I can reproduce your problem and NEST should not crash like this, but return a proper error message. But your  code is incorrect: You are calling `nest.SetDefaults()`, and default values have to be fixed values. You cannot provide a random distribution as a default value.

**Comment by heplesser** [comment] 2017-04-03 10:04
Looks like duplicate of #545.

**Comment by heplesser** [comment] 2017-04-04 10:25
Closing as duplicate of #545.

**Closed by heplesser** 2017-04-04 10:25 UTC
Labels: C: Kernel, I: No breaking change, P: Pending, S: Low, T: Bug
