### ISSUE TITLE
nest-similator.org broken on MacOS

### ISSUE THREAD

**Issue by gewaltig** [nest/nest-simulator#402] opened 2016-06-19 11:53 UTC
The nest-simulator.org site does nor display properly on Chrome and Safari.
<img width="1146" alt="screen shot 2016-06-19 at 13 50 25" src="https://cloud.githubusercontent.com/assets/2889878/16177142/2e89664e-3625-11e6-92e5-313f14ad569a.png">

**Comment by heplesser** [comment] 2016-06-19 20:42
@steffengraber I can confirm the problem on Safari 9.1.1 under OSX 10.10.5. Safari also does not display the graphics, but at least it does not let the figure caption into the menu below.

**Comment by lekshmideepu** [comment] 2016-06-19 21:39
It works fine with me on Safari 9.0.2 under OSX 10.11.2

**Comment by steffengraber** [comment] 2016-06-20 05:32
Hi  @gewaltig  and @heplesser 
I need some more information.
Could you please go to nest-simulator.org again and open the Safari Console. I think you can do that with:

1. Command-Option-I (Web Inspector) 
2. Command-Option-C (Console)

If this do not work, open the Safari Web Inspector and find the console, like it is described here: https://developer.apple.com/library/mac/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html

Please copy the complete content of the console, post it here or send it separately  to me.

**Comment by heplesser** [comment] 2016-06-20 07:11
@steffengraber Now it works (and I am rather certain that it has worked in the past as well, but definitely not last night).  

Note: To get to the Web Inspector/Console, one first needs to go to Preferences > Advanced and check off "Show Develop menu in menu bar". Then one finds Inspector and Console in the Develop submenu.

**Comment by heplesser** [comment] 2016-06-23 13:33
@steffengraber I made an interesting observation today using Safari: If I am on the nest-simulator.org page and click either "About NEST" or the NEST logo, the page is loaded in the garbled form shown in the screenshot above. When I then click "Reload" (or reach the page by entering its address in the address field), the page is rendered correctly. This behaviour was reproducible.

Not sure whether that is a bug on the page or in Safari.

**Comment by steffengraber** [comment] 2016-06-23 13:47
Hi @heplesser 

could you please go to the garbled page, open the Safari Console and send the complete content of it to me.
This would be very helpful, because I can not reproduce this error.

**Comment by gewaltig** [comment] 2016-06-23 13:56
I gett the same messed up page on Chrome and Safari, so I am not sure Safari is to blame.

**Comment by gewaltig** [comment] 2016-06-23 14:06
My stats are
MacOS 10.11.5 (15F34)
Chrome Version 51.0.2704.103 (64-bit)
Version 9.1.1 (11601.6.17)

And @heplesser reload trick does not work for me...

**Comment by gewaltig** [comment] 2016-06-23 14:18
Here is a transcript of the safari error log:

[Warning] Invalid CSS property declaration at: * (flexslider.css, line 63)
[Warning] Invalid CSS property declaration at: * (flexslider.css, line 82)
[Warning] Unexpected CSS token: : (advps-style.css, line 73)
[Warning] Unexpected CSS token: : (advps-style.css, line 88)
[Warning] Unexpected CSS token: : (advps-style.css, line 98)
[Warning] Invalid CSS property declaration at: * (advps-style.css, line 144)
[Warning] Invalid CSS property declaration at: * (advps-style.css, line 188)
[Warning] Invalid CSS property declaration at: * (advps-style.css, line 189)
[Warning] Invalid CSS property declaration at: ; (www.nest-simulator.org, line 56)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (brunel_alpha_nest-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (brette_gerstner_fig_2c-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (precise_spiking-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (mc_neuron-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (one_neuron_with_noise-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (style.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (style.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (brunel_delta_nest-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (sinusoidal_poisson_generator-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (tsodyks_facilitating-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (balancedneuron-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (multimeter_file-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (sinusoidal_gamma_generator-624x416.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (pulsepacket-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (one_neuron-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (brunel_alpha_numpy-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (BrodyHopfield-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (tsodyks_depressing-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (structural_plasticity-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (brette_gerstner_fig_3d-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (intrinsic_currents_subthreshold-624x468.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (testiaf-624x468.png, line 0)

**Comment by heplesser** [comment] 2016-11-17 13:59
This works now, thus closing.

**Closed by heplesser** 2016-11-17 13:59 UTC
Labels: C: Documentation
