### ISSUE TITLE
Exception messages are lost when using PyNEST

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1432] opened 2020-02-17 12:09 UTC
When using PyNEST, if an exception is thrown at the C++ level, e.g. BadProperty, the whole process (including Python interpreter) will crash with the following text:
```
terminate called after throwing an instance of 'nest::BadProperty'
  what():  BadProperty
```
followed by an unhelpful stack trace. The message (e.g. `"Synaptic weights for conductance-based multisynapse models must be positive."` if the original exception was `BadProperty("Synaptic weights for conductance-based multisynapse models must be positive.")`) is lost.

I am not sure what the best solution would be. A quick workaround is to add print statements to the exception constructors (BadProperty, BadParameter, etc.) in https://github.com/nest/nest-simulator/blob/master/nestkernel/exceptions.h. 

@jougs: do you know if there's any way to percolate these messages up from C++ to Python?

**Comment by heplesser** [comment] 2020-02-17 13:41
@clinssen The message is lost due to NEST crashing. We then only get minimal information about the exception. I suspected that this could be due to spike delivery not being properly wrapped using `try-except`, so that exceptions thrown in thread-parallel context would "leak" from [`handle(SpikeEvent&)`](https://github.com/nest/nest-simulator/blob/8b70004e6d03fd48b91028235b3d94c273779f1e/models/aeif_cond_alpha_multisynapse.cpp#L612). 

But the following reproducer
```python
nest.SetKernelStatus({'local_num_threads': 2})   
g = nest.Create('spike_generator', params={'spike_times': [1.0]}) 
n = nest.Create('aeif_cond_alpha_multisynapse', 4) 
nest.Connect(g, n, syn_spec={'receptor_type': 1, 'weight': -10.0})     
nest.Simulate(20)
```
triggers the exception under macOS with both 2.18.0 and 2.20.0, but it is properly caught and displayed.

**Comment by stinebuu** [comment] 2020-06-10 08:12
@heplesser Any updates on this?

**Comment by stinebuu** [comment] 2020-10-23 11:49
Closing this. If the error comes up again, please file a new issue.

**Closed by stinebuu** 2020-10-23 11:49 UTC
Labels: I: No breaking change, S: High, T: Bug
