### ISSUE TITLE
NEST failing to compile with libreadline and libncurses error in Mac Os Big Sur 11.0.1 (20B29)

### ISSUE THREAD

**Issue by dionperd** [nest/nest-simulator#1860] opened 2020-11-30 16:50 UTC
I tried to compile a module and I got the error below:

g++-9: error: /usr/lib/libreadline.dylib: No such file or directory
g++-9: error: /usr/lib/libncurses.dylib: No such file or directory

It used to compile just fine. First time I try after upgrading to Mac Os Big Sur it fails.

No problem with compiling the same module in a Linux Docker container.

I can provide the module, although, this must not be the problem, since:

Then, I tried to recompile NEST altogether, and I also got a similar error when running make:

 95%] Linking CXX shared library libmodels.dylib
[ 95%] Built target models
Scanning dependencies of target sli_readline
[ 95%] Building CXX object sli/CMakeFiles/sli_readline.dir/gnureadline.cc.o
make[2]: *** No rule to make target `/usr/lib/libreadline.dylib', needed by `sli/libsli_readline.dylib'.  Stop.
make[1]: *** [sli/CMakeFiles/sli_readline.dir/all] Error 2
make: *** [all] Error 2

**Desktop/Environment (please complete the following information):**
 - OS: Mac Os Big Sur 11.0.1 (20B29), Xcode 12.2 (12B45b), just installed the Command Line Tools for Xcode 12.2
 - Python-Version: Python 3.7.4, Anaconda
 - NEST-Version: NEST master branch 2c950e0d5 (November 30, evening)
 - Installation: 
cmake -DCMAKE_C_COMPILER=/usr/local/bin/gcc-9 -DCMAKE_CXX_COMPILER=/usr/local/bin/g++-9 -DCMAKE_INSTALL_PREFIX=/Users/dionperd/Software/NEST/nest3 -Dwith-mpi=/user/local/bin/mpic++ -Dwith-python=ON /Users/dionperd/Software/NEST/nest-simulator

**Comment by stinebuu** [comment] 2020-12-02 09:15
@dionperd Maybe this [e-mail thread](https://www.nest-initiative.org/mailinglist/hyperkitty/list/users@nest-simulator.org/thread/QKRQZOQ6DXPKV7QB7CSE3DVZ22HFAU52/) from the NEST-user mailinglist can be of help.

If not, @heplesser do you have time to have a look?

**Comment by heplesser** [comment] 2020-12-02 14:40
@dionperd The problem is just a missing readline library. I assume that you have installed gcc, cmake and openmpi using Homebrew, so `brew install readline` will probably do the trick. You may also want to `brew install gsl` to make sure that NEST also builds models with non-linear subthreshold dynamics. You should not really need the `-Dwith-mpi` and `-Dwith-python` flags, because NEST should find MPI automatically and Python is on by default. You can also configure NEST to build without readline using `-Dwith-readline=OFF`. This has no consequences if you use NEST only through the PyNEST interface from Python, but will make life less convenient if you are using NEST via the SLI interpreter.

**Comment by terhorstd** [comment] 2021-01-15 08:33
did this solve your issue, @dionperd ?

**Comment by dionperd** [comment] 2021-01-15 09:24
> did this solve your issue, @dionperd ?

I am still having trouble to install NEST in my laptop.
However, I need to research a little bit more and post the new problem(s), in an organized manner to not waste your time.
I will try to do it asap and get back to you.
It could be that just my environment is really messed up...

**Comment by heplesser** [comment] 2021-03-09 11:39
We have now revised the instructions for building NEST on Mac, see https://nest-simulator.readthedocs.io/en/latest/installation/mac_install.html.

Those instructions are for NEST 3, but they should also work for NEST 2. They are based on installing all dependencies via Conda and have been tested successfully also Apple Silicon (M1 CPU).

**Comment by terhorstd** [comment] 2021-03-26 09:32
Since this is fixed with #1918, I close this one.

**Closed by terhorstd** 2021-03-26 09:32 UTC
Labels: I: No breaking change, S: Normal, T: Bug
