### ISSUE TITLE
NEST installed via conda doesn't have enough permissions for `nest-config`

### ISSUE THREAD

**Issue by pnbabu** [nest/nest-simulator#2871] opened 2023-08-08 10:55 UTC
**Describe the bug**
NEST 3.5 installed via conda-forge does not have execute permissions for the `nest-config` file.
```
-rw-r--r--  1 user  staff   3.5K Aug  8 12:45 $HOME/miniconda3/envs/nest_3.5/bin/nest-config
```

**To Reproduce**
1. `conda install -c conda-forge nest-simulator`
2. Generate code for a NESTML model using the `generate_nest_target()` function which internally uses the `nest-config` file to build the generated code and create a dynamic `.so` file.
3. The below error is observed.
```
CMake Error at CMakeLists.txt:87 (message):
  Cannot run `/Users/pooja/miniconda3/envs/nest_3.5/bin/nest-config`.  Please
  specify correct `nest-config` via -Dwith-nest=...
```
4. The error is fixed after providing execute permissions to the file.
```
chmod +x $HOME/miniconda3/envs/nest_3.5/bin/nest-config
```

**Expected behavior**
The generated code should be built without any errors. This was the behavior until NEST version 3.4.

**Desktop/Environment (please complete the following information):**
 - OS: macOS 13.4.1
 - Python-Version: 3.11.4
 - NEST-Version: 3.5
 - Installation: conda

**Comment by steffengraber** [comment] 2023-08-10 05:55
Hi @pnbabu Thanks for reporting. I will take a look into it.

**Comment by steffengraber** [comment] 2023-08-24 05:55
@pnbabu I have now tested different conda environments with NEST. Directly after the installation of NEST the permissions of nest-config were set correctly. The tests were performed under Ubuntu 22.04.
Could you please create a conda environment again and check the permissions right after installation?

**Comment by pnbabu** [comment] 2023-08-24 13:49
@steffengraber I observed the permissions issue in MacOS. I created one environment with NEST 3.5 and one with NEST 3.3. The environment with 3.5 had issues with permissions and the one with 3.3 did not.

**Comment by heplesser** [comment] 2023-08-24 14:52
I can confirm @pnbabu's observations under macOS 13.5.1. I get the following:
```
rwxr-xr-x    1 plesser  staff  12146288 Aug 24 16:44 nest
-rw-r--r--    1 plesser  staff      3581 Aug 24 16:45 nest-config
-rwxr-xr-x    1 plesser  staff      3618 Aug 24 16:44 nest-config-bac
-rw-r--r--    1 plesser  staff      3579 Aug 24 16:45 nest-config-tmp
-rwxr-xr-x    2 plesser  staff      2922 Jul  4 19:59 nest-server
-rwxr-xr-x    2 plesser  staff      2244 Jul  4 19:59 nest-server-mpi
-rwxr-xr-x    2 plesser  staff       359 Jul  4 19:59 nest_indirect
-rwxr-xr-x    2 plesser  staff       355 Jul  4 19:59 nest_serial
-rwxr-xr-x    1 plesser  staff       330 Aug 24 16:44 nest_vars.sh
```
So everything has the `x` flag set except `nest-config` and `nest-config-tmp`.  Interestingly, `nest-config-bac`, which is a minute older than its two "siblings" has `x` set. I don't have time right now to find out how `nest-config` is created in our install process, but there might be something slightly off there. Could you try to find out how `nest-config` comes to be?

**Comment by heplesser** [comment] 2023-08-24 20:46
@steffengraber I have dug a little more and I think the problem is in the `post-link.sh` file:
https://github.com/conda-forge/nest-simulator-feedstock/blob/07374936d882ac6d028e6d1fe680822b9509aa29/recipe/post-link.sh#L19-L23

For Linux, `sed -i` modifies `nest-config` in place and that preserves the `x` permissions attribute. For macOS, on the other hand, `sed` produces new files which are created with normal file permissions, i.e. 644, not 755 as we would like.

But I think the two `sed` and two `mv` lines can be replaced by two `sed -i` lines, so we need no temporary files and no moves, and would keep the `x` in place:

```sh
sed -i "s|${COMPILER_FULL}|${COMPILER_RUN}|g" "${CONDA_PREFIX}"/bin/nest-config
sed -i "s|-fopenmp=libomp|-Xclang -fopenmp|g" "${CONDA_PREFIX}"/bin/nest-config
 ```

**Comment by steffengraber** [comment] 2023-08-28 10:47
I have integrated the solution. Many thanks @heplesser .
Additionally, I added a small test for the function of `nest-config` to the CI and extended all tests to MacOSX. 
The integrated tests did not show any problem.
It will take another 1-2 hours until the new packages are available. @pnbabu it would be nice if you could test it again then.

**Comment by steffengraber** [comment] 2023-09-01 06:33
Close it because it's done.

**Closed by steffengraber** 2023-09-01 06:33 UTC
Labels: T: Bug, S: Normal
